### ISSUE TITLE
Search for apps outside `/Applications`

### ISSUE THREAD

**Issue by Flamefork** [KELiON/cerebro#1]
Trying to find&launch `/Users/flamefork/Development/tizen-studio/TizenStudio.app`.

Quick comparison with Spotlight:

![screenshot 2016-11-16 20 37 50](https://cloud.githubusercontent.com/assets/20203/20356006/bc991cbc-ac3c-11e6-9dd9-884ea7e2656e.png)
![screenshot 2016-11-16 20 37 58](https://cloud.githubusercontent.com/assets/20203/20356012/bf726330-ac3c-11e6-9201-af5396adbf54.png)

**Comment by KELiON** [comment]
@Flamefork 👍 Fixed in [version 0.0.2](https://github.com/KELiON/cerebro/releases/tag/0.0.2)
