### ISSUE TITLE
Console often displays setState errors

### ISSUE THREAD

**Issue by staff0rd** [KELiON/cerebro#10]
> Warning: setState(...): Can only update a mounted or mounting component. This usually means you called setState() on an unmounted component. This is a no-op. Please check the code for the Preload component.

Looks like promise needs to be cancelled in unMount;
https://facebook.github.io/react/blog/2015/12/16/ismounted-antipattern.html

**Comment by KELiON** [comment]
@staff0rd I thought about adding it, but after some investigation I found, that it is just a warning in development mode, and in production this `setState` just ignored. `makeCancellable` approach is not real cancellation of HTTP request, it is just skipping `setState` after component unmounted. Eventually, adding this `makeCancellable` will increase code base size and complexity without any advantages.

What I decided, is some time later rewrite all `fetch(url)` statements to some node-based library to fetch data with an ability to cancel requests, not just skip `setState`.

**Comment by BrainMaestro** [comment]
These errors are actually preventing my plugin from working. They occur everytime I try to use an external component for `getPreview` for the display function. What exactly is causing them, and how do I get around it? It doesn't have any issues if I use an inline element.

**Comment by KELiON** [comment]
@BrainMaestro can you share your code example?

**Comment by BrainMaestro** [comment]
[getPreview Issue](https://github.com/BrainMaestro/cerebro-stackoverflow/tree/show-preview-issue)

It works normally on the master branch. Thanks for checking
