### ISSUE TITLE
Module version mismatch. Expected 50, got 48.

### ISSUE THREAD

**Issue by BrainMaestro** [KELiON/cerebro#101]
I pulled in the new updates on the cerebro app, and now I get that error while trying to run the plugin I'm developing. Not sure what the issue is this time. I mentioned I was having a separate issue yesterday. Cerebro plugin development is a little frustrating right now. Should I hold off until things are more stable?

**Comment by KELiON** [comment]
@BrainMaestro hey! Did you try [that](https://github.com/KELiON/cerebro#resolve-common-issues)?

**Comment by BrainMaestro** [comment]
That works. Thanks! Sorry I overlooked it.
