### ISSUE TITLE
Content in preview is cut if it is too long

### ISSUE THREAD

**Issue by BrainMaestro** [KELiON/cerebro#106]
I'm developing a plugin. I noticed an issue with the preview where it won't show all the content possible when it gets to a certain length. That is, you won't be able to scroll up to that point. Any idea what's wrong?

Here's a screenshot 
<img width="808" alt="screen shot 2017-02-09 at 2 14 40 pm" src="https://cloud.githubusercontent.com/assets/1738373/22784956/7c3daf4c-eed2-11e6-83c3-a616a9f6bf5c.png">

**Comment by KELiON** [comment]
@BrainMaestro from this screenshot I can't guarantee that I understood an issue, but I think it is related to vertical alignment of the preview. By default it is shown in the middle, but if height is bigger than window height you can't reach top of the preview. Am I correct?

If so you have to add css-rule for your root element: `align-self: flex-start;`, like in [cerebro-imdb](https://github.com/KELiON/cerebro-imdb/blob/master/src/Preview/styles.css#L1) plugin.

**Comment by BrainMaestro** [comment]
Sorry the screenshot didn't show it well but you're right. It happens exactly as you specified. Any idea why that happens? I'm curious.

Anyway, your suggestion works very well. Thanks for being helpful.
