### ISSUE TITLE
Launch Cerebro on system startup

### ISSUE THREAD

**Issue by chesterhow** [KELiON/cerebro#119]
I'm currently using Cerebro on my Windows machine and I'm kinda surprised why it hasn't been suggested yet, but perhaps there should be an option to automatically launch Cerebro on system startup.

Or has it already been implemented and mine's just bugging out? If it's not yet implemented then I think this would definitely be really useful to have.

Great app btw! Been searching for an Alfred alternative for Windows for the longest time, and I'm so glad I found this 😄

**Comment by KELiON** [comment]
@chesterhow glad that you like it! I also had this idea and plan to include it to the next release

**Comment by chesterhow** [comment]
Awesome! I'll look out for the next update and in the meantime close this issue.

**Comment by stevemao** [comment]
Is it available now?

**Comment by KELiON** [comment]
@stevemao not yet(

**Comment by stevemao** [comment]
Ok, just don't want this to be forgotten :)
