### ISSUE TITLE
Extract bundled functionality into independent plugins that can be disabled

### ISSUE THREAD

**Issue by maximbaz** [KELiON/cerebro#121]
This suggestion is one outcome of the #118. I would like to see less functionality bundled together with the app, and instead shipped as independent plugins. 

For example, I personally would like to disable:
- File search and preview (especially because the process running it consumes 100mb of RAM even when not used)
- Google search (also mentioned in #32).

It is totally fine though to pre-install some plugins together with the app, the default functionality should not be hurt. I only want the ability to remove these plugins.

**Comment by KELiON** [comment]
Done in version 0.3.0
