### ISSUE TITLE
[Question] Updating plugins

### ISSUE THREAD

**Issue by BrainMaestro** [KELiON/cerebro#122]
How are plugins updated when a new version is released? Does the user have to update them or is it handled automatically?

**Comment by KELiON** [comment]
@BrainMaestro hey! Now it is manual process – user searches plugin by name and choose update option. But I'm going to add autocheck and autoupdate

**Comment by BrainMaestro** [comment]
Cool, if you point me in the right direction, I'd love to help somehow

**Comment by KELiON** [comment]
@BrainMaestro sure! I just want to check versions of all installed plugins once in a while (i.e. once in 3-4 hours) and for all outdated plugins just do an update (uninstall + install) and reload an app after updating of all plugins. 

Best place to do this check is [initializeAsync](https://github.com/KELiON/cerebro/blob/master/docs/plugins/plugin-structure.md#initializeasync) method of [plugins](https://github.com/KELiON/cerebro/blob/master/app/main/plugins/core/cerebro/plugins/index.js) plugin (I didn't find better name 😀).

**Comment by BrainMaestro** [comment]
Okay I'll take a closer look tomorrow. Just a thought however, what if the update system was similar to the way Atom handles package updates? There would be a visual identifier of pending somewhere unobtrusive, but easy to see. That way, it's the user's choice on when to update.

**Comment by BrainMaestro** [comment]
Haven't been able to figure out how to do this. Maybe you can pick it up if you still want to
