### ISSUE TITLE
Unable to launch Discord (Windows)

### ISSUE THREAD

**Issue by chesterhow** [KELiON/cerebro#123]
![screenshot 23](https://cloud.githubusercontent.com/assets/9312956/23022306/090239bc-f48b-11e6-96df-a423ca74c473.png)

When I type "Discord" it shows a url instead of the app's filepath. When I hit enter, a little window pops up for a split second and disappears right away. And Discord doesnt get launched.

Anyone else facing this bug?

**Comment by theweavrs** [comment]
Can confirm this.

**Comment by KELiON** [comment]
#144 should fix it! Can you try [this build](https://www.dropbox.com/s/hylenaysj374lqg/Cerebro%20Setup%200.2.6.exe?dl=0)?

**Comment by chesterhow** [comment]
@KELiON It works now! Small issue though, it now shows 2 listings of Discord. Both of which are able to launch Discord perfectly fine.

**Comment by KELiON** [comment]
@chesterhow I suppose it is because you have two `.lnk` files in your system. Can you please try to open file location using `ctrl+r` from Cerebro for both files and post these locations here?

**Comment by chesterhow** [comment]
Both lead to the same file location. But if I'm not wrong it seems I have 2 versions of Discord :o
![capture14](https://cloud.githubusercontent.com/assets/9312956/23260241/d4d40266-fa0b-11e6-834b-eb2cb75213f1.PNG)

**Comment by mistic100** [comment]
I had the problem with Chrome apps, I confirm this build works, thank you.
