### ISSUE TITLE
Start with the SO

### ISSUE THREAD

**Issue by rafa-acioly** [KELiON/cerebro#130]
Is there any way to start the App along with the OS? (I'm currently starting through terminal)

**Comment by CrashyBang** [comment]
On linux? You should have a "Startup applications" utility that you can point to `/usr/bin/cerebro`.

NOTE: I am not sure if that is the right path :)

**Comment by luisdavim** [comment]
On Linux this is easy to achieve, but how can it be done in OS X?

**Comment by rafa-acioly** [comment]
@CrashyBang No files are generated in the / usr / bin folder :(
i'm using ubuntu 16.04

@luisdavim can you say how can i do it?

**Comment by rafa-acioly** [comment]
I found the solution.

I first copied the `.AppImage` file to the `/ usr / bin` folder and then added it to `gnome-session-properties`

**Comment by luisdavim** [comment]
@rafa-acioly that depends on what DE you are using, for example on i3 you add
```
exec --no-startup-id <command-that-you-normally-use>
```
On Gnome and Unity you can create a .desktop file under ```~/.config/autostart/``` that looks something like this:
```
[Desktop Entry]
Type=Application
Name=<Name of application as displayed>
Exec=<command to execute>
Icon=<full path to icon>
Comment=<optional comments>
X-GNOME-Autostart-enabled=true
```

I hope this helps.

**Comment by luisdavim** [comment]
I've also found the solution for OS X, go to:
1. - System Preferences>Users & Groups.
2. - Select your User ID.
3. - Select Login Items.
4. - Click the lock icon and enter and admin password.
5. - Click the + button to select an app from your Applications folder.
6. - Or drag app icons across to Startup Items.
