### ISSUE TITLE
[Problem] Windows Plugin Development

### ISSUE THREAD

**Issue by tenorz007** [KELiON/cerebro#132]
Changes aren't updated immediately in symlink. I have to close the link and create it again.

**Comment by KELiON** [comment]
@tenorz007 hey! Can you please give me more details? Do you use [boilerplate](https://github.com/KELiON/cerebro-plugin)? What do you see in terminal output when something changes? What are you doing after your changes, how do you close the link and create it again?

**Comment by tenorz007** [comment]
I am using the boilerplate, I am able to load the plugin. However when I make changes to the code the terminal outputs the file that I changed but yet it doesn't seem to show up on the app. So I have to keep killing the symlink and run it again whenever I make a change.

**Comment by KELiON** [comment]
@tenorz007 can you try to update the file and use `development` → `reload` from tray menu?

**Comment by tenorz007** [comment]
I do that, it logs that the change is noticed however when I run the plugin alas the change isn't updated.
Someone else has this issue #153

**Comment by KELiON** [comment]
@tenorz007 Can you try latest [cerebro-plugin](https://github.com/KELiON/cerebro-plugin), maybe [this PR](https://github.com/KELiON/cerebro-plugin/pull/7) fixes this problem
