### ISSUE TITLE
No file search in elementary OS

### ISSUE THREAD

**Issue by JLIT0** [KELiON/cerebro#133]
All functions other than file search perform as expected.

When executed from the terminal, the following error appears:

`Gtk-Message: Failed to load module "pantheon-filechooser-module"`

**Comment by dar5hak** [comment]
I'm on elementary OS Loki, and file search works for me.

Quoting the readme:

> Navigate in file system with file previews (i.e. ~/Dropbox/passport.pdf);

Did you try typing the path like it says above?

(Also, the warning you see is harmless, [says Daniel Foré](https://bugs.launchpad.net/elementaryos/+bug/1525664).)

**Comment by KELiON** [comment]
@JLIT0 currently Cerebro doesn't have files search, only apps search and files navigation (using `~/Dropbox/passport.pdf or `/Something/my_file.png`). 

Adding files search is already in the issue #115
