### ISSUE TITLE
Currency symbols not recognized

### ISSUE THREAD

**Issue by dar5hak** [KELiON/cerebro#136]
### Steps to reproduce

- __Case 1:__ Type <kbd>113 ₣</kbd>
- __Case 2:__ Type <kbd>113 chf</kbd>

### Expected behaviour

Cerebro converts it to the local currency in both cases and displays the result in the text box.

### Actual behaviour

It only converts case 2.

### System info

elementary OS 0.4, based on Ubuntu 16.04

---

@maximbaz mentioned in #126 that symbol recognition only works for <kbd>$</kbd>, <kbd>€</kbd> and <kbd>£</kbd>. I confirmed that behaviour.

**Comment by KELiON** [comment]
[Fixed](https://github.com/KELiON/cerebro-converter/pull/5) in converter@1.0.1
