### ISSUE TITLE
Get applications list on Windows

### ISSUE THREAD

**Issue by KELiON** [KELiON/cerebro#14]
Find a way to get list of all installed applications on Windows

**Comment by skys215** [comment]
In Launchy, there's a default list of directory to find the applications. Like `C:\Program Files\` for Windows, and can specify the file type which you want to add to index, like `.exe` on Windows.

**Comment by gluons** [comment]
Windows UWP apps are in `C:\Program Files\WindowsApps` but you need **Administrator** right to access this folder.

**Comment by KELiON** [comment]
If someone want to try applications on windows there is a [beta build](https://www.dropbox.com/s/wkc1lncjtx00rpy/Cerebro%20Setup%200.2.3.exe?dl=0).

**Comment by KELiON** [comment]
I've implemented simple search for `.lnk` and `.exe` files in [3 directories](https://github.com/KELiON/cerebro/compare/feature/windows-apps?expand=1#diff-9febaa8a20fe54d121024454fcaf13d9R7). 

I found another way to use Power Shell: https://blogs.technet.microsoft.com/heyscriptingguy/2013/11/15/use-powershell-to-find-installed-software/, but it doesn't work for built-in applications, like wordpad or OneDrive, so maybe later we can continue to dig in this direction

**Comment by Kageetai** [comment]
@KELiON seems to work for a first version, although no icons are display
![image](https://cloud.githubusercontent.com/assets/1738309/22442251/f5f16850-e73a-11e6-8026-4c60df447857.png)

**Comment by KELiON** [comment]
@Kageetai awesome! I still don't have an idea about getting file icon on windows, but there is another issue for that #16

**Comment by Kageetai** [comment]
Maybe this would help: http://sciencevikinglabs.com/icon-extractor/

**Comment by KELiON** [comment]
@Kageetai already tried it, but it didn't work for me on windows 10(

**Comment by KELiON** [comment]
Another test build with some improvements in #62
