### ISSUE TITLE
Uncaught TypeError: Cannot read property 'startsWith' of undefined

### ISSUE THREAD

**Issue by matmunn** [KELiON/cerebro#140]
This afternoon I've noticed that I can no longer start apps with Cerebro - they're not in my search results.

I opened up in devtools and am presented with the following:
![image](https://cloud.githubusercontent.com/assets/65853/23246938/380789d2-f9eb-11e6-8ea4-f50da14c75cf.png)

I can attach a live stack trace, it just didn't copy nicely.

**Comment by KELiON** [comment]
@matmunn interesting! I hope #141 will fix it. Can you check [this build](https://www.dropbox.com/s/ru6jnfg32c3sco2/Cerebro-0.2.6.dmg?dl=0)?

**Comment by matmunn** [comment]
Hey @KELiON, I've installed the build you linked and it all seems to be ok. I'll close this issue for now and reopen or create another one if the problems pops back up again.

**Comment by KELiON** [comment]
@matmunn thanks!
