### ISSUE TITLE
Control + Backspace deletes the whole line

### ISSUE THREAD

**Issue by tunnckoCore** [KELiON/cerebro#143]
I'm used to ctrl+backspace to just delete previous word, so is any chance to fix that behavior?

**Comment by KELiON** [comment]
@tunnckoCore wow, I didn't know about this behaviour. Is it default shortcut? On which OS?

**Comment by tunnckoCore** [comment]
ArchLinux.

> Is it default shortcut?

I believe yes. It is available on any input type=text, i believe? Try google input field or any other form out there. If i remember the dark times on windows before couple of years it was existing there too.

**Comment by KELiON** [comment]
On MacOS it just clears whole input. Thanks for report, I'll fix it
