### ISSUE TITLE
Launch Apps on Linux

### ISSUE THREAD

**Issue by scmanjarrez** [KELiON/cerebro#146]
Hi, 
Is there any command to execute apps on Linux (Ubuntu 16.04.2 LTS, Gnome, Cerebro 0.2.6 installed via .deb), I typed some apps in the search box but only google search/translation is prompted.

![screenshot from 2017-02-23 15-06-18](https://cloud.githubusercontent.com/assets/9284124/23262109/c84cd84c-f9d9-11e6-91e6-6a0554d8fdf3.png)

**Comment by KELiON** [comment]
@scmanjarrez hey! Can you please do the following: 

1) Open settings
2) Turn on developer mode, show icon in tray
3) From tray icon choose development -> DevTools (background)
4) From tray icon choose development -> reload
5) And after that send me output of `console` tab of devtools?

**Comment by scmanjarrez** [comment]
Hi, 
Thanks for the answer.

![screenshot from 2017-02-23 15-13-32](https://cloud.githubusercontent.com/assets/9284124/23262357/ab302ca4-f9da-11e6-9852-3424bfceeaf3.png)

**Comment by scmanjarrez** [comment]
It seems like an error of my previous team viewer app, I've deleted that file (.desktop) and now is working properly.
Thanks.
