### ISSUE TITLE
Uncaught (in promise) TypeError: Cannot read property 'replace' of undefined

### ISSUE THREAD

**Issue by matmunn** [KELiON/cerebro#149]
I upgraded to the build linked in #140 and now I still can't launch applications.

The stack trace has changed to the below:
```
main.bundle.js:41362 Uncaught (in promise) TypeError: Cannot read property 'replace' of undefined(…)
main.bundle.js:41362 Uncaught (in promise) TypeError: Cannot read property 'replace' of undefined(…)
main.bundle.js:41362 Uncaught (in promise) TypeError: Cannot read property 'replace' of undefined(…)
main.bundle.js:41362 Uncaught (in promise) TypeError: Cannot read property 'replace' of undefined(…)
main.bundle.js:41362 Uncaught (in promise) TypeError: Cannot read property 'replace' of undefined(…)
main.bundle.js:41362 Uncaught (in promise) TypeError: Cannot read property 'replace' of undefined(…)
main.bundle.js:41362 Uncaught (in promise) TypeError: Cannot read property 'replace' of undefined(…)
main.bundle.js:41362 Uncaught (in promise) TypeError: Cannot read property 'replace' of undefined(…)
main.bundle.js:41362 Uncaught (in promise) TypeError: Cannot read property 'replace' of undefined(…)
main.bundle.js:41362 Uncaught (in promise) TypeError: Cannot read property 'replace' of undefined(…)
main.bundle.js:41362 Uncaught (in promise) TypeError: Cannot read property 'replace' of undefined(…)
main.bundle.js:41362 Uncaught (in promise) TypeError: Cannot read property 'replace' of undefined(…)
main.bundle.js:41362 Uncaught (in promise) TypeError: Cannot read property 'replace' of undefined(…)
main.bundle.js:41362 Uncaught (in promise) TypeError: Cannot read property 'replace' of undefined(…)
main.bundle.js:41362 Uncaught (in promise) TypeError: Cannot read property 'replace' of undefined(…)
main.bundle.js:41362 Uncaught (in promise) TypeError: Cannot read property 'replace' of undefined(…)
main.bundle.js:41362 Uncaught (in promise) TypeError: Cannot read property 'replace' of undefined(…)
main.bundle.js:41362 Uncaught (in promise) TypeError: Cannot read property 'replace' of undefined(…)
main.bundle.js:41362 Uncaught (in promise) TypeError: Cannot read property 'replace' of undefined(…)
main.bundle.js:4849 [rpc] emit showTerm
main.bundle.js:41362 Uncaught (in promise) TypeError: Cannot read property 'replace' of undefined(…)
main.bundle.js:41362 Uncaught (in promise) TypeError: Cannot read property 'replace' of undefined(…)
main.bundle.js:41362 Uncaught (in promise) TypeError: Cannot read property 'replace' of undefined(…)
main.bundle.js:41362 Uncaught (in promise) TypeError: Cannot read property 'replace' of undefined(…)
main.bundle.js:41362 Uncaught (in promise) TypeError: Cannot read property 'replace' of undefined(…)
main.bundle.js:41362 Uncaught (in promise) TypeError: Cannot read property 'replace' of undefined(…)
main.bundle.js:41362 Uncaught (in promise) TypeError: Cannot read property 'replace' of undefined(…)
main.bundle.js:41362 Uncaught (in promise) TypeError: Cannot read property 'replace' of undefined(…)
main.bundle.js:41362 Uncaught (in promise) TypeError: Cannot read property 'replace' of undefined(…)
main.bundle.js:4849 [rpc] emit showTerm
```

It seems to reference cachedAppsList so I'm thinking this might be where the problem stems from. Is there a way to flush the cached apps so I can see if that fixes it?

**Comment by maximbaz** [comment]
> Is there a way to flush the cached apps so I can see if that fixes it?

Quit the app, remove the `apps_cache.json` file [in the same folder where config is located](https://github.com/KELiON/cerebro#config-file-path), start the app again.

**Comment by matmunn** [comment]
I had a look there and that file didn't exist. Is there anywhere else it could be located?

**Comment by maximbaz** [comment]
Apparently that is a location of cache file on Windows / Linux only, which means you are probably on Mac :) 

After a quick look over the code it doesn't seem like the Mac apps are cached on disk, actually. So the app restart should be enough, I imagine. But I might be wrong :)

**Comment by matmunn** [comment]
Correct, I'm on a Mac.

I tried poking around in the stack trace and the code a little, but I'm not very familiar with Electron apps.

If the cached apps aren't persisted to disk then how would it be loading them to run through the cached apps function?

**Comment by maximbaz** [comment]
I see a [memoized function](https://github.com/KELiON/cerebro/blob/master/app/main/plugins/core/osx-apps/index.js#L36-L41) which is [periodically invalidated](https://github.com/KELiON/cerebro/blob/master/app/main/plugins/core/osx-apps/index.js#L84-L90), so my guess is that all the apps are being searched for the first time when the app starts (no cache on startup), the results are then memoized in the function itself, and the memoized function is reset [on interval](https://github.com/KELiON/cerebro/blob/master/app/main/plugins/core/osx-apps/index.js#L89) or [when a new app is installed](https://github.com/KELiON/cerebro/blob/master/app/main/plugins/core/osx-apps/index.js#L94).

**Comment by matmunn** [comment]
It's strange, I just left Cerebro running for a while and it's picked up my applications.

I restarted the program and they're still there - I haven't installed any new programs or deleted any old ones. No idea what is going on there.

**Comment by KELiON** [comment]
@matmunn interesting, let us know if it happens again

**Comment by matmunn** [comment]
@KELiON I'll close this for now and let you know if it happens again. Thanks guys
