### ISSUE TITLE
When trying to update plugin, uninstalls instead

### ISSUE THREAD

**Issue by codingmatty** [KELiON/cerebro#154]
This is hard to recreate, but I noticed there were the option to `uninstall`, `update`, or `details`, and when I tried to `update` it actually uninstalled the plugin instead. Then I have to go back to the plugin to reinstall.

**Comment by codingmatty** [comment]
I see this line, it uninstalls and then installs, but I guess it doesn't get back to the install part

https://github.com/KELiON/cerebro/blob/5e36eb25031ea25a395289fbe8de1dc102a8d723/app/lib/plugins/npm.js#L100

**Comment by KELiON** [comment]
@codingmatty looks like something happened during uninstallation. Can you check console and copy output here is you have this problem again?

**Comment by codingmatty** [comment]
Closing this, since the last time I did it it worked. Fluke, I suppose?

**Comment by KELiON** [comment]
@codingmatty anyway should not be a case after #157. Now plugin is removed only when new version is downloaded and extracted to temp folder
