### ISSUE TITLE
Can't see rounded corner here

### ISSUE THREAD

**Issue by miftahafina** [KELiON/cerebro#160]
I just tried to install Cerebro in my Ubuntu 16.04 with unity desktop, but there's no rounded corner like on cerebro's homepage.

![screenshot from 2017-02-26 08-12-32](https://cloud.githubusercontent.com/assets/5361135/23336199/5cec845c-fbfb-11e6-8c9e-4d63472c0af9.png)

**Comment by AlexAlabyev** [comment]
@miftahafina there's no rounded corners on windows as well. I suppose it's using system's styles and showing up only on MacOS

**Comment by KELiON** [comment]
@miftahafina screenshots on Cerebro's website was captured on MacOS and this option depends on OS
