### ISSUE TITLE
Add to electron.atom.io/apps

### ISSUE THREAD

**Issue by wilomgfx** [KELiON/cerebro#168]
It should be added with all the great electron apps list :)
So that people can find it easier/discover whilst looking at electron apps.

here http://electron.atom.io/apps/

Thanks for making this amazing app. Ill be switching from alfred on my mac and from wox on my pc. Now i can use the same app on both :D

**Comment by AlexAlabyev** [comment]
I think it's already there, mate 

![1](https://cloud.githubusercontent.com/assets/13764106/23343572/b685abd2-fc7e-11e6-9b26-472018ee8bb6.PNG)

**Comment by wilomgfx** [comment]
Damn it is. I searched for : celebro ahhaa.!
