### ISSUE TITLE
Plugins unable to be triggered

### ISSUE THREAD

**Issue by mijoharas** [KELiON/cerebro#169]
Only error is:

```
main.bundle.js:95675 The provided value 'moz-chunked-arraybuffer' is not a valid enum value of type XMLHttpRequestResponseType.
```

all of the plugins I have tried installing do not work. `devdocs` `lipsum` and `linux` so far are ones I've tested. (tried typing in `devdocs`, `lipsum` and `shutdown` to test the respective plugins, but nothing but google search and translate seems to come up).

The plugins appear to have installed themselves, and when I install a new plugin nothing seems untoward in either of the consoles.

**Comment by maximbaz** [comment]
What I additionally observed is that after I install the plugin it is appearing in `~/.config/Cerebro/plugins/package.json`, but they are missing from `~/.config/Cerebro/plugins/node_modules`. 

Furthermore, running `npm install` from `~/.config/Cerebro/plugins` directory downloads the plugins and then they are working in cerebro.

**Comment by KELiON** [comment]
Hm, looks like I had to test properly #157 on Linux and Windows before merging it...

**Comment by mijoharas** [comment]
@maximbaz you're right, that looks like it's a decent workaround for now.
