### ISSUE TITLE
Cerebro can't be opened because it's not from identified developer

### ISSUE THREAD

**Issue by tarvos21** [KELiON/cerebro#172]
I have try to install Cerebro on macOS Sierra, after it's successfully installed into Applications, I try to open it, but it's says, Cerebro can't be opened because the developer is not identified. What's the problem? Anyone know? Thanks a lot.

**Comment by jauzeyimam** [comment]
Go to System Preferences -> Security & Privacy and you should see a subheading "Allow apps downloaded from."  If you change that to "Anywhere" MacOS will allow you to open Cerebro.

**Comment by tarvos21** [comment]
Oh, @jauzeyimam, thanks for your response, I don't know why there is no "Anywhere" choice on my computer, but I finally got to allow it by one command:
`spctl --add /Applications/Cerebro.app`
