### ISSUE TITLE
Javascript Error: unable to find registry key or value

### ISSUE THREAD

**Issue by saketh-bobby** [KELiON/cerebro#174]
**On Windows 10 and latest version of cerebro** right after installing the app startup fails due to this error

![2017-02-27](https://cloud.githubusercontent.com/assets/12474004/23364864/c2f7e756-fd26-11e6-933f-55012b047b44.png)

**Comment by maximbaz** [comment]
@KELiON this looks like a Windows version of #41 / #124, isn't it?

**Comment by saketh-bobby** [comment]
Yeah seems to be. So what's the solution.Update the machine-id dependency or something ? Or just checkout master and build ?

**Comment by maximbaz** [comment]
I think the workaround would be to manually create the registry key in place where the app is trying to find it. 

Also, have a look: https://github.com/automation-stack/node-machine-id/issues/9

**Comment by saketh-bobby** [comment]
Well most of them are saying that this arises because app is 64 bit but electron is 32 bit. So i guess installing 64 bit electron will work ? Or as you said manually creating registry key is the best solution ?

**Comment by KELiON** [comment]
@saketh-bobby after 3rd issue about `node-machine-id` I see that it is not stable and we have to eliminate errors of this package. I've fixed this issue in #176.

You can download test build with this fix [here](https://www.dropbox.com/s/hylenaysj374lqg/Cerebro%20Setup%200.2.6.exe?dl=0)

**Comment by saketh-bobby** [comment]
Even the test build is not working for me !! Same error

**Comment by SkaceKamen** [comment]
> I think the workaround would be to manually create the registry key in place where the app is trying to find it.

The key is there, the reg query just fails from unknown reason. The command (`%windir%\System32\REG QUERY ....`) works fine, when executed in console.

**Comment by saketh-bobby** [comment]
Yup the test build is working !!
