### ISSUE TITLE
[Feature/Plugin Request] brew formulas search and install

### ISSUE THREAD

**Issue by luisdavim** [KELiON/cerebro#180]
Hi,

in macOS I use [homebrew](https://brew.sh/) and it would be cool if cerebro could search and install brew formulas, maybe it could search by scraping http://searchbrew.com/ or http://brewformulas.org/ 

There is also [linuxbrew](http://linuxbrew.sh/) but I'm not aware of any search page for it's formulas.

**Comment by KELiON** [comment]
@luisdavim nice! I'd also use this plugin. Implementation looks simple: there is an endpoint, like http://searchbrew.com/search?q=formula. I'd not include installation inside plugin, just open terminal with entered `brew install formula`

**Comment by luisdavim** [comment]
I'll give it a try to implement it myself. If you are not working on it.

**Comment by KELiON** [comment]
@luisdavim no, i'm not. I think you can use [cerebro-npm](https://github.com/jordanadams/cerebro-npm) as a basis

**Comment by setegonz** [comment]
0.2.7 release is not available through homebrew. Will this version be available anytime soon?

**Comment by KELiON** [comment]
@setegonz sorry for the delay. It will be available in brew cask as soon as [this PR](https://github.com/caskroom/homebrew-cask/pull/30572) is merged

**Comment by luisdavim** [comment]
Hi, here's my first attempt at it:
https://github.com/luisdavim/cerebro-brew

I still need to update the README file and this doesn't work 100% for my case because I'm using tmux and the text gets pasted into the terminal before tmux is initialized, I can increase the delay before pasting the text but that might give a bad experience to who has their terminals initializing faster.

Can you try it out and let me know if you have any suggestions?

Thanks,
Luis

**Comment by luisdavim** [comment]
I've updated the readme file and published the plugin.

**Comment by KELiON** [comment]
@luisdavim looks great! Do you think that this plugin should react to everything included? I'd like to see brew results only when I type something like `brew ruby-build`

**Comment by luisdavim** [comment]
you're right, I'll look into that.

**Comment by luisdavim** [comment]
@KELiON I've updated the plugin the work as you described.
