### ISSUE TITLE
Replacing toggle shortcut with Command + Space

### ISSUE THREAD

**Issue by kylewebdev** [KELiON/cerebro#181]
When trying to make the shortcut to toggle Cerebro the same as Spotlight on MacOS, I cannot use `Command + Space` as a shortcut, even after disabling all MacOS shortcuts that use `Command + Space`.

**Comment by joydo** [comment]
I have this same problem , there is any efficient method for solving this issue ??  Online Waiting !!!!!

**Comment by bpatram** [comment]
Same issue here, running version `0.2.6`. Seems like Cmd+Space is the only shortcut I can't set it to

**Comment by bpatram** [comment]
@kylewebdev See https://github.com/KELiON/cerebro/issues/100#issuecomment-282732820

I had the same issue, try closing and re-opening Cerebro after removing the default Spotlight key shortcut

**Comment by kylewebdev** [comment]
@bpatram Thanks!

**Comment by KELiON** [comment]
@kylewebdev can you confirm that it solves your issue?

**Comment by exislow** [comment]
I can confirm.
