### ISSUE TITLE
MyAnimeList Integration

### ISSUE THREAD

**Issue by alucard0134** [KELiON/cerebro#184]
for us weeb degenerates who use this app would appreciate to look up our animus with ease

pls & thx

**Comment by dar5hak** [comment]
That's a great idea for an external plugin you could write! Check out the [plugin docs](https://github.com/KELiON/cerebro/blob/master/docs/plugins.md) to learn how.

**Comment by alucard0134** [comment]
man i already am too depressed with other shit

**Comment by lubien** [comment]
If you could wait until next week I volunteer to make this plugin @alucard0134.
Using cerebro will be way better than [my CLI app](https://github.com/lubien/popura-cli)

**Comment by lubien** [comment]
[Done](https://github.com/lubien/cerebro-mal)

**Comment by alucard0134** [comment]
![i love you](https://a.safe.moe/nA4HU.GIF)

**Comment by lubien** [comment]
![](http://i.imgur.com/NNzJ8G8.gif)
