### ISSUE TITLE
[Feature Request] Ctrl+Enter key automatically appends .com TLD to word

### ISSUE THREAD

**Issue by simsketch** [KELiON/cerebro#188]
ie: stackoverflow `Ctrl+Enter` will open stackoverflow.com

Thanks for considering this feature!

**Comment by KELiON** [comment]
@simsketch I suppose you are going to use this feature only for sites, that you are visiting a lot (I think for other sites in most cases you're going to use search).

So, what you can do now is to "teach" cerebro. I.e. open cerebro, type stackoverflow.com and open this url. After that, when you type `stack` you'll have suggestion:

![screen shot 2017-02-28 at 22 44 36](https://cloud.githubusercontent.com/assets/594298/23435355/98349258-fe07-11e6-921a-56318d5d7db7.png)

So you don't even need to type whole address, just type `stack` and use `enter`

**Comment by simsketch** [comment]
Well, that works for me! thanks!
