### ISSUE TITLE
Window stays open when choosing a suggestion

### ISSUE THREAD

**Issue by staff0rd** [KELiON/cerebro#19]
## Window hides on enter ✅ 

**REPRO**

1. Open cerebro window
2. Type "anything"
3. Hit enter

**EXPECTED & ACTUAL**
Browser opens, cerebro hides

## Window does not hide on enter :x:

**REPRO**
1. Open cerebro window
2. Type "anything"
3. Arrow over to suggestion list
4. Hit enter

**EXPECTED**
Browser opens, cerebro hides

**ACTUAL**
Browser opens, cerebro stays open

**Comment by KELiON** [comment]
Looks like it is related to https://github.com/KELiON/cerebro/issues/20, because in production environment with developer mode turned off Cerebro window is hidden when focus lost
