### ISSUE TITLE
Download Links are not working on website

### ISSUE THREAD

**Issue by cseale** [KELiON/cerebro#190]
https://cerebroapp.com

Download for mac link fails every time

**Comment by narekvardanjan** [comment]
Tried wget from github release page. It seems amazon-cloud doesn't respond.

**Comment by KELiON** [comment]
@cseale unfortunately it is uploaded to Amazon S3 that has problems now, you can check their status [here](https://status.aws.amazon.com/) (Amazon Simple Storage Service (US Standard))

**Comment by KELiON** [comment]
@cseale if you want you can use one of these dev. builds:

MacOS:
https://www.dropbox.com/s/ru6jnfg32c3sco2/Cerebro-0.2.6.dmg?dl=0

Windows:
https://www.dropbox.com/s/hylenaysj374lqg/Cerebro%20Setup%200.2.6.exe?dl=0

Linux .deb: 
https://www.dropbox.com/s/hy4p58nsom9p3i1/cerebro_0.2.6_amd64.deb?dl=0

Linux .AppImage
https://www.dropbox.com/s/h8h98wb78bfov3a/cerebro-0.2.6-x86_64.AppImage?dl=0

It can be not stable, so if you have any problms just download stable version from website, when Amazon S3 is back:)
