### ISSUE TITLE
When installing plugins, allow manual reload

### ISSUE THREAD

**Issue by codingmatty** [KELiON/cerebro#193]
I have had to setup 2 new computers in the last few weeks, and going in and installing all the plugins that I want becomes tedious, because it reloads after each installation. Hopefully, I won't have to setup a new computer for a long time, but I could see it being a hurdle for not only new users, but also as there are more and more plugins it becomes harder to look through all them and install the new ones that you may want, and then install another new one, etc.

**Comment by KELiON** [comment]
@codingmatty already solved! In #157 I've implement real-time plugin loading, so you don't even need to reload app, plugin is loaded automatically after installation
