### ISSUE TITLE
Dark theme

### ISSUE THREAD

**Issue by perfectum1** [KELiON/cerebro#2]
Add dark OS X theme

**Comment by KELiON** [comment]
@perfectum1 do you have examples of good dark themes for other apps? Would be cool to have a list of themes, that users use now

**Comment by perfectum1** [comment]
@KELiON dark theme as the spotlight: https://up.kibakoapp.com/UfqbKrEM0w

**Comment by perfectum1** [comment]
@KELiON I drew a mockup for a dark theme - https://www.dropbox.com/s/qi1e46xy9v01d23/cerebro-dark.png?dl=0

**Comment by KELiON** [comment]
@perfectum1 awesome! I've added dark theme in [version 0.0.3](https://github.com/KELiON/cerebro/releases/tag/0.0.3): 

![screen shot 2016-11-19 at 21 48 52](https://cloud.githubusercontent.com/assets/594298/20458323/ff42ca24-aea1-11e6-8f59-f6a4fc92b370.png)

**Comment by perfectum1** [comment]
@KELiON круто! По-русски напишу. Можешь еще добавить немного воздуха и сделать отступы как на мокапе. Будет больше похоже на спотлайт и приятней глазу :) Могу скинуть мокап в зеплине. Что думаешь?

**Comment by perfectum1** [comment]
И еще возможно бэкграунд блюр для фона сделать?

**Comment by KELiON** [comment]
@perfectum1 да, можно по-русски) Ну то что будет больше похоже на стоплайт это скорее минус, мне наоборот бы хотелось куда-то в сторону от него по дизайну уйти. Если есть какие-то идеи — буду рад послушать.

Но отступы увеличу, да) Скинешь ссылку?

Blur добавлю, но чуть позже, т.к. это не просто стили, нужно будет версию движка (electron) обновлять.

**Comment by perfectum1** [comment]
@KELiON только увидел сообщение. Напиши свою почту я расшарю мокап
