### ISSUE TITLE
Hide on lose focus

### ISSUE THREAD

**Issue by staff0rd** [KELiON/cerebro#20]
Would like the option for cerebro to hide when the window loses focus, for example;

1. Open cerebro
2. Click on another window
3. cerebro hides

**Comment by KELiON** [comment]
@staff0rd currently it works, but only in production environment and when developer mode (from preferences) turned off: 

![](http://g.recordit.co/afC0g7j3a9.gif)

It is needed in development environment/mode for developer tools. It is annoying when you open developer tools and move focus there – main windows is hidden and it is harder to debug UI
