### ISSUE TITLE
Awesome Cerebro

### ISSUE THREAD

**Issue by lubien** [KELiON/cerebro#205]
I'm currently in love with this app and I can't stop thinking in how to improve it with plugins.

I just made an [awesome list for Cerebro](https://github.com/lubien/awesome-cerebro). It'd be a good way to build a community-driven list of useful resources to Cerebro developers/users.

It also decouples the plugin list from your README so no need to commit here just to update the list.

I hope you like the idea.

**Comment by tiagoamaro** [comment]
Many plus ones for this one. Since plugins can be freely generated by Cerebro's users, managing a plugin list at the main README will be unbearable. Having an awesome list for this is a 💯!

**Comment by gluons** [comment]
This is awesome.
Have you PR to [sindresorhus/awesome](https://github.com/sindresorhus/awesome)?

**Comment by KELiON** [comment]
@lubien can you do a PR to change current Readme? So you can just remove all plugins from the main readme and replace it with link to awesome-cerebro

**Comment by lubien** [comment]
@gluons I will!
@KELiON sure ASAP

**Comment by lubien** [comment]
@gluons 

As of [Pull Request Template of sindresorhus/awesome](https://github.com/sindresorhus/awesome/blob/master/pull_request_template.md):
* The list I added
   * **has been around for at least 30 days,**
    ...others

So I'm gonna delay this PR :)
