### ISSUE TITLE
Install plugins from npm?

### ISSUE THREAD

**Issue by IniZio** [KELiON/cerebro#206]
So cerebro-npm is not on the plugins list on my cerebro installation and i tried to install it by doing `yarn add cerebro-npm` on the `.config/Cerebro/plugins` folder, but after restart it does not seem that Cerebro recognised the newly installed plugin?

**Comment by lubien** [comment]
See #194 and #203

**Comment by IniZio** [comment]
So there already is an unmerged fix? Thanks!
