### ISSUE TITLE
Ubuntu 16.04: Error in the terminal

### ISSUE THREAD

**Issue by gusbemacbe** [KELiON/cerebro#207]
I installed `nodejs` before, but when I tried to install `cerebro` via terminal, I got an error:

```
$ cd cerebro && yarn && cd ./app && yarn && cd ../
ERROR: There are no scenarios; must have at least one.
```
Thank you for your attention!

**Comment by dar5hak** [comment]
Get rid of the && and try those commands one by one. Which one yields the error?

**Comment by gusbemacbe** [comment]
It still gave the same error, but I discovered something.

It was prevented by `cmdtest` installed from Ubuntu. I removed `cmdtest` and replaced for `yarn` installed from `npm install yarn`, after ugrading to `nodejs 7`. 

Unfortunately, after running `cd cerebro && yarn && cd ./app && yarn && cd ../`, it gave some errors of compatibility and download, Cerebro started, but after closing the terminal, Cerebro app does not start anymore. I saved two texts, one with script-commanded and another without script-commanded via terminal (I selected and copied all) and attach them for you.

Terminal 1 - clean copy of all the terminal
Terminal 2 - copy from script

[terminal.txt](https://github.com/KELiON/cerebro/files/818184/terminal.txt)
[terminal2.txt](https://github.com/KELiON/cerebro/files/818185/terminal2.txt)

**Comment by KELiON** [comment]
@gusbemacbe looks like terminal2.txt is cut.  Can you attach full version?

Also, still would be better if you can run command-by-command and see where you have an issue: 

```
cd cerebro
yarn 
cd ./app
yarn 
cd ../
```

**Comment by gusbemacbe** [comment]
Here are the three separated files output from script via terminal. 

[1 - cd cerebro && yarn.txt](https://github.com/KELiON/cerebro/files/832422/cd.cerebro.yarn.txt)
[2 - cd ./app && yarn.txt](https://github.com/KELiON/cerebro/files/832424/cd.app.yarn.txt)
[3 - cd ../ && yarn run dev.txt](https://github.com/KELiON/cerebro/files/832426/cd.yarn.run.dev.txt)

**Comment by joseph-zhong** [comment]
I'm running Ubuntu 14.04 and I believe I have the same issue, if I just run `yarn` I get `ERROR: There are no scenarios; must have at least one.`

**Comment by KELiON** [comment]
@joseph-zhong you also run yarn from `cmdtest`, uninstall it with `sudo apt remove cmdtest`.


More details: https://github.com/yarnpkg/yarn/issues/2821
