### ISSUE TITLE
My plugin not showing on Mac

### ISSUE THREAD

**Issue by ReeSilva** [KELiON/cerebro#209]
Hey guys.

I developed the plugin [cerebro-vagalume-plugin](https://www.npmjs.com/package/cerebro-vagalume-plugin). On my Linux notebook the plugin showed successfully when I search for plugins and I can install and use it, ok!

But on my Mac the plugin doesn't appear when I search. There's anything that I need to do to my plugin appears as an option on Mac?

Regards.

**Comment by JordanAdams** [comment]
@ReeSilva Looks like this could be related to the fix made in https://github.com/KELiON/cerebro/pull/194. However it doesn't look like that change has been released yet.

**Comment by KELiON** [comment]
@ReeSilva @JordanAdams yes, it is related and fixed, I'm going to release it today
