### ISSUE TITLE
Uncaught Error: Cannot find module "./preview/Archive" on Arch Linux

### ISSUE THREAD

**Issue by matmunn** [KELiON/cerebro#210]
This is a fresh install of the v0.2.6-1 package from the AUR.

Upon pressing Ctrl+Space I get nothing but a white window, I had to manually enable developer mode to be able to see the console to get the error.

**Comment by matmunn** [comment]
The AppImage version appears to be working.

**Comment by KELiON** [comment]
@matmunn you can try to use `cerebro-git` instead of `cerebro` AUR – it is the latest version with all fixes. Let me know if it works for you (`cerebro` will be fixed with next release, today I think)
