### ISSUE TITLE
[Split plugins to categories | 0.2.7] doesn't work on Windows OS

### ISSUE THREAD

**Issue by AlexAlabyev** [KELiON/cerebro#212]
It looks like **[Split plugins to categories | 0.2.7]** doesn't work on Windows OS
Can anybody else confirm this?

In this example, I installed the Clipboard plugin, but it didn't go up on the top. App restart didn't help

![screenshot 935](https://cloud.githubusercontent.com/assets/13764106/23578497/6f938996-00e9-11e7-9e3a-5cafc4c401fa.png)

**Comment by maximbaz** [comment]
Curious how could this functionality be OS-specific, but yes, it doesn't repro on Linux.

**Comment by AlexAlabyev** [comment]
@maximbaz that what I was wondering. Well, maybe PR [https://github.com/KELiON/cerebro/pull/208](https://github.com/KELiON/cerebro/pull/208) didn't make it to the .exe of the 0.2.7 build ?

**Comment by maximbaz** [comment]
That's relatively easy to check, open DevTools (main) from the tray icon, hit <kbd>Ctrl+Shift+F</kbd> to search in all files, enter `categorize` and hit <kbd>Enter</kbd>.

If that code made into your app, you will see this:

![image](https://cloud.githubusercontent.com/assets/1177900/23578677/c758fd4e-00dc-11e7-971f-1fac259dd341.png)

Also check if you see any errors in the console tab.

**Comment by AlexAlabyev** [comment]
@maximbaz there's no errors in the console. The `categorize` const is not there. So I guess, it didn't make it to the .exe after all

![1](https://cloud.githubusercontent.com/assets/13764106/23578721/58c3cd7a-00ee-11e7-95b3-d4342069d486.PNG)

**Comment by tiagoamaro** [comment]
@maximbaz, after reading your comment, I wondered why my packaged 0.2.7 didn't have this feature as well (running on macOS). I just cloned the repo, ran `yarn run package` on latest master, and now I have all features described at the release changelog.

Probably, windows version (as macOS version) wasn't created on 0.2.7 commit as reported at https://github.com/KELiON/cerebro/releases/tag/0.2.7.

Comparing it's md5 hashes for the 0.2.7 version commit (https://github.com/KELiON/cerebro/tree/292d9c43c603d87106a9042cc86f7c23df0256d9), my packaged `.dmg` md5 hash is `78109b5b95f4647d71c8b57eb9dfe266`, while the one on Github is `cc5d484be452fdc164fef0030ada6d68`.
