### ISSUE TITLE
unable to upgrade or install new version

### ISSUE THREAD

**Issue by helionmelion** [KELiON/cerebro#214]
hello, today I tried to upgrade and then to uninstall and reinstall to cerebro 0.2.7-2 from AUR (archlinux) but found this error:

0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'run', 'build' ]
2 info using npm@4.3.0
3 info using node@v7.7.1
4 verbose run-script [ 'prebuild', 'build', 'postbuild' ]
5 info lifecycle cerebro@0.2.7~prebuild: cerebro@0.2.7
6 silly lifecycle cerebro@0.2.7~prebuild: no script for prebuild, continuing
7 info lifecycle cerebro@0.2.7~build: cerebro@0.2.7
8 verbose lifecycle cerebro@0.2.7~build: unsafe-perm in lifecycle true
9 verbose lifecycle cerebro@0.2.7~build: PATH: /usr/lib/node_modules/npm/bin/node-gyp-bin:/home/ia/.cache/pacaur/cerebro/src/cerebro-0.2.7/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/bin:/usr/lib/jvm/default/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl
10 verbose lifecycle cerebro@0.2.7~build: CWD: /home/ia/.cache/pacaur/cerebro/src/cerebro-0.2.7
11 silly lifecycle cerebro@0.2.7~build: Args: [ '-c', 'yarn run build-main && yarn run build-renderer' ]
12 info lifecycle cerebro@0.2.7~build: Failed to exec build script
13 verbose stack Error: cerebro@0.2.7 build: `yarn run build-main && yarn run build-renderer`
13 verbose stack spawn ENOENT
13 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/lib/utils/spawn.js:33:16)
13 verbose stack     at emitTwo (events.js:106:13)
13 verbose stack     at ChildProcess.emit (events.js:194:7)
13 verbose stack     at maybeClose (internal/child_process.js:899:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
14 verbose pkgid cerebro@0.2.7
15 verbose cwd /home/ia/.cache/pacaur/cerebro/src/cerebro-0.2.7
16 error Linux 4.9.11-1-ARCH
17 error argv "/usr/bin/node" "/usr/bin/npm" "run" "build"
18 error node v7.7.1
19 error npm  v4.3.0
20 error file sh
21 error code ELIFECYCLE
22 error errno ENOENT
23 error syscall spawn
24 error cerebro@0.2.7 build: `yarn run build-main && yarn run build-renderer`
24 error spawn ENOENT
25 error Failed at the cerebro@0.2.7 build script 'yarn run build-main && yarn run build-renderer'.
25 error Make sure you have the latest version of node.js and npm installed.
25 error If you do, this is most likely a problem with the cerebro package,
25 error not with npm itself.
25 error Tell the author that this fails on your system:
25 error     yarn run build-main && yarn run build-renderer
25 error You can get information on how to open an issue for this project with:
25 error     npm bugs cerebro
25 error Or if that isn't available, you can get their info via:
25 error     npm owner ls cerebro
25 error There is likely additional logging output above.
26 verbose exit [ 1, true ]

**Comment by maximbaz** [comment]
Hey @helionmelion, thanks for the notice, I completely forgot to update build steps to use `yarn` instead of `npm`. Please try again on `0.2.7-3` and let me know if you still experience this issue.

**Comment by helionmelion** [comment]
it works now thank you very much!
