### ISSUE TITLE
Quite many plugins cannot be installed, failing on `requirePlugin`

### ISSUE THREAD

**Issue by maximbaz** [KELiON/cerebro#217]
The logs in the console are pretty much the same for all of the affected plugins:

```
Load plugin: cerebro-devdocs
main.bundle.js:30583 Path: /home/maximbaz/.config/Cerebro/plugins/node_modules/cerebro-devdocs...
main.bundle.js:30546 Error requiring /home/maximbaz/.config/Cerebro/plugins/node_modules/cerebro-devdocs
main.bundle.js:30547 SyntaxError: Unexpected token }
    at Object.exports.runInThisContext (vm.js:76:16)
    at Module._compile (module.js:528:28)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at requirePlugin (file:///usr/lib/cerebro/resources/app.asar/dist/main.bundle.js:30543:20)
    at FSWatcher.module.exports.pluginsWatcher.on.pluginPath (file:///usr/lib/cerebro/resources/app.asar/dist/main.bundle.js:30584:19)
```

I tried quite a few plugins, can reproduce with:

- devdocs
- stackoverflow
- hash
- imdb
- timestamp

However the `clipboard` plugins can be installed just fine. 

Is this really a separate issue with every single plugin, or rather something fishy with Cerebro itself?

**Comment by AlexAlabyev** [comment]
Just tried to install stackoverflow and imdb plugins on Windows [build 0.2.7]. And it works fine.

But the 0.2.7 build for Windows doesn't have the "plugin sorting" function, as you remember from [https://github.com/KELiON/cerebro/issues/212](https://github.com/KELiON/cerebro/issues/212). Could it be that this is what causing the problem on Linux then?

**Comment by maximbaz** [comment]
Yeah, I'm not sure on what code the Windows build is based 🙂 

Maybe you could test in a dev version? Or package a Windows installer for yourself, based on the 0.2.7 release code, or even on the latest `master`? 🙂  

It's not very different from [running a dev build](https://github.com/KELiON/cerebro#install), I think the packaging command is `yarn run package`, and you would be able to verify both this and #212 issues 🙂

**Comment by KELiON** [comment]
@maximbaz did you try to remove all plugins from config folder → plugins/node_modules?

**Comment by maximbaz** [comment]
Just tried that on dev build (not to break my working cerebro), removed entire `~/.config/Electron/plugins` folder, restarted the app, tried to install `devdocs` and `imdb` - same issue with "Invalid or unexpected token". The plugin files are appearing under `plugins/node_modules` folder, but are failing upon require.

I take it, it doesn't repro on Mac either?

**Comment by KELiON** [comment]
@maximbaz no, everything is ok on Mac. Tested in prod build and dev.

Node and Chromium versions are fixed in the app and doesn't depend on system. Fact that it works on windows and mac, but doesn't work on Linux is weird. 

I have only one idea of debugging it: can you try to remove these packages, download source code of one of them (lets do it with devdocs, it is easy to debug, because I've created this plugin) and run `npm install && npm run debug` from this plugin?

**Comment by maximbaz** [comment]
Just did that, plugin loaded, everything is working fine. Could it be an issue only with code minification? But it's weird that you don't reproduce it...

**Comment by KELiON** [comment]
@maximbaz you can also try it: run `npm run build` and create symlink to the plugin (you can copy symlink path from `scripts/debug`). It will be the same version of code that is published to npm

**Comment by maximbaz** [comment]
I can't believe I didn't try this earlier, but here it is: the plugin fails to load only when being installed, if I restart Cerebro, the plugin will work.

This is still weird, as during installation all the files are present in the correct location (it says it cannot parse the file, not that it cannot find the file), and again, this issue doesn't happen to all plugins - the `clipboard` plugin has no issues at all, and works immediately after installation.

**Comment by maximbaz** [comment]
I figured it out, it is a race condition. Have a look at #219, perhaps you have better ideas how to fix it.

**Comment by KELiON** [comment]
Can we close this @maximbaz?

**Comment by maximbaz** [comment]
Yes, seems all right
