### ISSUE TITLE
Icon appears jagged in Windows

### ISSUE THREAD

**Issue by staff0rd** [KELiON/cerebro#22]
I briefly saw icons included in the latest commits - possibly the reason why the icon is displayed low quality in windows now;
![image](https://cloud.githubusercontent.com/assets/6289998/22004387/3f586f2a-dcaf-11e6-9c1d-3a7738c0a841.png)

**Comment by KELiON** [comment]
@staff0rd is it tray icon? Was it like this before, when you managed to launch an app on windows?

**Comment by staff0rd** [comment]
Strangely it is only one of my windows machines that displays this symptom - environmental I guess.
