### ISSUE TITLE
Plugin settings in the settings UI

### ISSUE THREAD

**Issue by BrainMaestro** [KELiON/cerebro#222]
Some plugins need to be able to store settings. An example would be an `API_KEY` for the stackoverflow plugin to prevent rate limiting, but there are many possible scenarios. I'm not sure how the plugin authors currently implement it, but wouldn't it be nice if a plugin can register the settings it needs, and those options show up in the cerebro settings under a category for the app. Similar to how iOS handles app settings.

The format could be `key`: `type`
```javascript
module.exports = {
  fn: fn,
  settings: {
     API_KEY: 'string'
  }
}
```

**Comment by KELiON** [comment]
I think it is necessary feature and I had it in my backlog! Would be nice if someone can help me with implementation of it. Do you want to start it @BrainMaestro?

### As I see it
We can use [json-schema](http://json-schema.org/) for plugin settings keys. When all plugins loaded we know which of them include `settings` key, so we can display inputs for these plugins in current "settings" view. Also we can reuse existing input elements (dropbowns, inputs, checkboxes) from existing settings.

These settings could be just stored in the global config file.

**Comment by BrainMaestro** [comment]
Yeah that's a good idea. I'll start it.
