### ISSUE TITLE
Can't map hotkey to ALT+Space from Settings GUI

### ISSUE THREAD

**Issue by Abhinav1217** [KELiON/cerebro#223]
I was trying to map cerebro to ALT+SPACE key. I wasn't able to do that via the settings GUI. I finally managed to achieve this by manually editing the config file via text editor. But Having able to do it via GUI is not possible.

**Comment by arendon1** [comment]
Hey @Abhinav1217 Do you mind elaborate a little bit more on the process? i'm trying to achieve the same task. Thanks in advance for your troubles.

**Comment by KELiON** [comment]
@Abhinav1217 @arendon1 maybe comments in #181 or #100 can help. If you use MacOS you have to check that desired hotkey is not used by system (i.e. by Spotlight), restart Cerebro and try to map it again

**Comment by Abhinav1217** [comment]
I am on Fedora 25 Gnome on wayland. I have unmapped the hotkey from Gnome, so it is now available to map with cerebro. I don't have any other application which uses this hotkey.  I have mapped it to cerebro by manual editing like I said above, but can't still map it via settings GUI in the app.

I tried it on other spins on fedora on VM (I am a maintainer of [Fedy](https://github.com/folkswithhats/fedy) so I have all spins in VMs ready ) and it worked fine on KDE and XFCE ( even when this hotkey is used by the DE ) but not with Gnome wayland. It did work on Gnome Xorg but I had to unmap hotkey from DE. Maybe you can find some pattern from this info.

Off the topic, I really love it and I hope you don't mind if I add cerebro to Fedy. Its a tool which helps Fedora users to easily install software which fedora does not ship, and do system tweaks.

**Comment by KELiON** [comment]
> I hope you don't mind if I add cerebro to Fedy

@Abhinav1217 awesome, of course I don't mind!

Regarding hotkey mapping in Gnome – did you try to restart Cerebro after you unmapped hotkey from Gnome?

**Comment by arendon1** [comment]
Regarding my case, i'm on a debian based with custom form scratch DE called deepin, i found no easy way to unbind the `Alt+Space` binding, but just forcing it into Cerebro `config.json` i was able to map the hotkey before the DE register, i also needed to restart the computer in order to get working that.

**Comment by Abhinav1217** [comment]
@KELiON Yup. Restarted the whole os. Just checked once again I can't make this on GUI. Had to re-map it via manual editing of config file. But works great otherwise. Almost no crashes past few days of usage. The crashes I had was me messing with it so don't worry about it.

**Comment by jedahan** [comment]
I was able to remap to alt+space on macOS 10.12.4, Cerebro 0.2.7 installed via homebrew

**Comment by KELiON** [comment]
Will be included in next release!

**Comment by Abhinav1217** [comment]
Thanks.  I almost forgot about this.
