### ISSUE TITLE
How to install plugins in bulk.

### ISSUE THREAD

**Issue by Abhinav1217** [KELiON/cerebro#224]
How can I install plugins in bulk. Something like shell command which I can use to install multiple plugins on a fresh installed system.

**Comment by maximbaz** [comment]
That's easy, backup your `CONFIG_DIR/plugins/package.json` ([how to find CONFIG_DIR](https://github.com/KELiON/cerebro#config-file-path)), restore this file on the freshly installed system, and from that folder run `npm install`.

**Comment by Abhinav1217** [comment]
Thanks.
