### ISSUE TITLE
Multiple instances on windows possible

### ISSUE THREAD

**Issue by Schrims** [KELiON/cerebro#229]
On windows it seems to be possible to run multiple instances of the application.
This could be solved using [single-instance](https://github.com/electron/electron/blob/master/docs/api/app.md#appmakesingleinstancecallback).

![image](https://cloud.githubusercontent.com/assets/9212161/23741024/a95dc87e-04a6-11e7-98c8-70d0d18ae747.png)

![image](https://cloud.githubusercontent.com/assets/9212161/23741042/ca6b676a-04a6-11e7-8515-d085b637c3cd.png)

**Comment by KELiON** [comment]
@Schrims would be great if you can do a PR. Looks like it is one-line fix, but have a big value! Unfortunately it is hard for me to test Cerebro on windows, so even if I do this fix I'll have to wait someone to test it. 

Let me know if you can do it or if you need any help!
