### ISSUE TITLE
Application and file icons not displayed under windows

### ISSUE THREAD

**Issue by provalinf** [KELiON/cerebro#231]
Hello everyone,
I found (after a lot of trouble) your spotlight which is much more successful than what I have tested so far, excellent work continue like this!

Concerning the problem, I think you must already know it, but in doubt, no icon is displayed for applications and files under Windows.
If ever the OS version is important, I'm running Windows 7.
![cerebro_2017-03-11_00-57-58](https://cloud.githubusercontent.com/assets/15704455/23817739/c84986f6-05f5-11e7-8bb1-f574be85425e.png)

Thank you

**Comment by maximbaz** [comment]
It's being worked on here: https://github.com/KELiON/cerebro/pull/198
There's even a test build with this functionality implemented, you are welcome to try it and provide feedback on that page.

**Comment by provalinf** [comment]
Oops, I had not seen, thank you for the info.
