### ISSUE TITLE
Starting app on windows fails

### ISSUE THREAD

**Issue by matueranet** [KELiON/cerebro#24]
I just downloaded the windows release and I get two dialog popups:

    The program can't start because node.dll is missing from your computer. Try reinstalling the program to fix this problem.

The other dialog states (comes after I click OK on the first one):

    The program can't start because ffmpeg.dll is missing from your computer. Try reinstalling the program to fix this problem.

**Comment by KELiON** [comment]
@matueranet I've added [windows installer](https://github.com/KELiON/cerebro/releases/download/0.2.1/Cerebro.Setup.0.2.1.exe) instead of .exe application file. It should fix your issue. Can you try it please?

**Comment by Flascher** [comment]
I was having this issue as well, and Cerebro now opens without any errors after running the installer.

**Comment by matueranet** [comment]
Thanks it works now. I am amazed at how fast it is! Was earlier looking at zazuapp, but thinking of making the switch.

**Comment by KELiON** [comment]
@matueranet awesome, thank you! On Windows and Linux it still needs a lot of work, but I'm trying to improve it :)

**Comment by matueranet** [comment]
@KELiON If you are looking for a Windows Beta tester or want to have something tested on Windows, just send me a build. I would be happy to test it a few days and report any issues I might encounter.

**Comment by oftob** [comment]
Hello, there. I have same problem with autostart Cerebro. node.dll and ffmpeg.dll
