### ISSUE TITLE
[minor] Cannot set "Control+/" as a Shortcut

### ISSUE THREAD

**Issue by Ribtoks** [KELiON/cerebro#243]
OS: Windows 10 x64
When I press Ctrl+"/" just nothing happens.

**Comment by navdeepio** [comment]
same issue here, cannot set it to "Super + Space"

**Comment by maximbaz** [comment]
@Ribtoks you can use the workaround from #223 and set `Ctrl+/` via editing config file.

**Comment by Ribtoks** [comment]
@maximbaz Yup, proves to work. Thanks!

**Comment by KELiON** [comment]
Anyway, it is just workaround and we will fix this bug

**Comment by KELiON** [comment]
Will be included in next release!
