### ISSUE TITLE
System applications

### ISSUE THREAD

**Issue by navdeepio** [KELiON/cerebro#245]
Can cerebro search for the installed applications, say with .desktop files? By default it doesn't seem to do that..

**Comment by KELiON** [comment]
@navdeepio hi! What OS do you use? Can you also share some absolute path of installed application that is not found by Cerebro? 

Also, would be great if you can check console.log of main and background windows. To do it:

* open cerebro preferences
* turn on developer mode, show in menu bar
* in tray menu open development -> Dev. Tools (Main), Dev. Tools (background)
* In tray menu choose development -> reload
* Check both developer tools windows in console tab. If you see any errors – attach screenshot/text from this tab

**Comment by navdeepio** [comment]
hi @KELiON I installed the aur package 'cerebro' in place of cerebro-git, and it seems to work now.

**Comment by aleclarson** [comment]
Cerebro cannot find applications in `~/Applications`, but it was working for months. Any ideas?

macOS Sierra v10.12.3
Cerebro v0.2.8

**Comment by aleclarson** [comment]
@KELiON Looks like it's only having problems with application aliases. Thoughts?

**Comment by KELiON** [comment]
@aleclarson actually, there is no crawler, it uses index of Spotlight. So if you can find this application in Spotlight – it should be visible in Cerebro. Can you try it?

**Comment by aleclarson** [comment]
@KELiON Can confirm. Thanks!
