### ISSUE TITLE
[Question] Does Cerebro learn frequently used applications?

### ISSUE THREAD

**Issue by TheConnMan** [KELiON/cerebro#249]
On Windows I search "Power" for Powershell and the one I want is the fifth in the list. I thought after I scrolled down and selected that one a few times Cerebro would start promoting it in the search results because it's what I always choose.

If frequently accessed apps aren't promoted in search results maybe someone could point me in the direction of where that could be implemented and I could try my hand at a PR.

**Comment by AlexAlabyev** [comment]
@TheConnMan it has been proposed in [https://github.com/KELiON/cerebro/issues/91](https://github.com/KELiON/cerebro/issues/91) already. As @maximbaz suggested it can be implemented using a simple counter

**Comment by KELiON** [comment]
Thanks for initiative, @TheConnMan! Let's track you status in your PR: #250
