### ISSUE TITLE
[Feature Request] Auto-updates

### ISSUE THREAD

**Issue by Stanzilla** [KELiON/cerebro#251]
Should be easy to implement via Electron/Squirrel, no?

**Comment by wilomgfx** [comment]
Already does update by itself

Ref : https://github.com/KELiON/cerebro/blob/master/app/AppUpdater.js

**Comment by Stanzilla** [comment]
@wilomgfx doesn't look like it does anything else than send me to the download page on Windows though.

**Comment by KELiON** [comment]
@Stanzilla looks like it doesn't work now, after few updates (but it was tested and worked!) because I published new release yesterday and don't see auto update on my working machine. I'll try to figure it out

**Comment by KELiON** [comment]
@Stanzilla btw, what OK do you use? I hope now autoupdate will work, so if you restart your Cerebro on version 0.2.7 after few minutes you should get latest version automatically

**Comment by Stanzilla** [comment]
I will have to try later on but I was under the impression that using the `Check for updates` tray icon option was going to trigger an auto-update but that directs you to the download on github instead so I might just be confused.
