### ISSUE TITLE
Webpack INVALID watch not triggered on windows

### ISSUE THREAD

**Issue by staff0rd** [KELiON/cerebro#26]
Works on mac, not on windows - file changes do not trigger a bundle rebuild.

**Comment by KELiON** [comment]
@staff0rd interesting. Do you have an experience with webpack and modules reloading on windows? Did it work? If so, can you share webpack config that works on windows?

**Comment by KELiON** [comment]
Now recommended way to develop plugins is [create-cerebro-plugin](https://github.com/KELiON/create-cerebro-plugin). It has hot-reloading of plugin code
