### ISSUE TITLE
Differentiate between opening a new app's instance vs switching to existing?

### ISSUE THREAD

**Issue by amsheppard** [KELiON/cerebro#260]
- [x] I am on the [latest](https://github.com/KELiON/cerebro/releases/latest) Cerebro.app version
- [x] I have searched the [issues](https://github.com/KELiON/cerebro/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: Elementary OS 0.4, Loki (Ubuntu 16.04) 
- **Cerebro.app version**: 0.2.7_amd64.deb 
- **Relevant information from devtools** _(See above how to open it)_: N/A 

## Issue

Is it possible to have Cerebro present the option to switch to a currently opened instance of an app rather than opening a new one? I have multiple copies of an app running but only sometimes want to spawn a new, blank app. (eg: switch to an existing instance vs opening a 'new' LibreOffice Writer). I can have upwards of two dozen+ 'windows' open at any given time & find it time consuming to navigate between them/time consuming to the numerous keystokes required via [alt] + [tab].

If such a feature showing this concept could be differentiated between the two actions, this would be very much appreciated.

**Comment by maximbaz** [comment]
#138

**Comment by KELiON** [comment]
Closing since it is duplicate. @amsheppard you can add your thoughts about @maximbaz's [solution](https://github.com/KELiON/cerebro/issues/138#issuecomment-289535535) in #138
