### ISSUE TITLE
Not registering *.desktop applications launchers from Snapd?

### ISSUE THREAD

**Issue by amsheppard** [KELiON/cerebro#262]
- [x] I am on the [latest](https://github.com/KELiON/cerebro/releases/latest) Cerebro.app version
- [x] I have searched the [issues](https://github.com/KELiON/cerebro/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: Elementary OS 0.4/Loki (Ubuntu 16.04) 
- **Cerebro.app version**: 0.2.7_amd64.deb  
- **Relevant information from devtools:** N/A 

## Issue
After a fresh install of ```snapd 2.22.6 amd64``` & the snap for Shotcut ```17.03 (5) 196MB classic```, Shotcut.desktop does not appear in Cerebro (it also doesn't appear in Loki's Application launcher). The location of shotcut.desktop is ```/snap/shotcut/current/Shotcut.desktop``` which seems to be outside of Cerebro's [default directory scanning](https://github.com/KELiON/cerebro/blob/master/app/main/plugins/core/basic-apps/linux.js#L9-L16).

It was installed using ```sudo snap install shotcut --classic``` as described on [this WebUpD8 article.](http://www.webupd8.org/2017/02/shotcut-video-editor-available-as-snap.html)

I do not know what other distro's default location are for snapd. This was the default on a Ubuntu 16.04 derivative.

(EDIT: typos)

**Comment by KELiON** [comment]
@amsheppard Can you add this path to [linux.js](https://github.com/KELiON/cerebro/blob/master/app/main/plugins/core/basic-apps/linux.js#L9-L16) and create PR?

**Comment by amsheppard** [comment]
How strange. Snaps for Shotcut version 17.04.02 & my other 'snap', Krita 3.1.1 (git 6bcc3352), are now showing & loading in Cerebro. I made no changes. Closing marking ID10T error. Thanks for the attention.
