### ISSUE TITLE
 ..

### ISSUE THREAD

**Issue by davydka** [KELiON/cerebro#264]
- [ ] I am on the [latest](https://github.com/KELiON/cerebro/releases/latest) Cerebro.app version
- [ ] I have searched the [issues](https://github.com/KELiON/cerebro/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: 
- **Cerebro.app version**: 
- **Relevant information from devtools** _(See above how to open it)_:

**Comment by KELiON** [comment]
What is it?
