### ISSUE TITLE
Dark theme font color issue

### ISSUE THREAD

**Issue by sepehr** [KELiON/cerebro#269]
- [x] I am on the [latest](https://github.com/KELiON/cerebro/releases/latest) Cerebro.app version
- [x] I have searched the [issues](https://github.com/KELiON/cerebro/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: macOS 10.12.4
- **Cerebro.app version**: 0.2.7
- **Relevant information from devtools**: N/A

## Issue
When I enable the dark theme, the font color is not right: 

![cerebro dark theme font color issue](https://cloud.githubusercontent.com/assets/23576/24699536/8980ccb8-1a09-11e7-8bc2-286f7d768c89.png)

I restarted Cerebro, still no change.

**Comment by KELiON** [comment]
@sepehr can you please add a list of installed plugins? Looks like some plugin overrides some styles

**Comment by sepehr** [comment]
@KELiON Here:

```
cerebro-base64
cerebro-clipboard
cerebro-devdocs
cerebro-emoj
cerebro-gif
cerebro-github
cerebro-hash
cerebro-imdb
cerebro-ip
cerebro-kill
cerebro-lipsum
cerebro-osx-eject
cerebro-osx-system
cerebro-reload
cerebro-rot13
cerebro-shell
cerebro-stackoverflow
cerebro-timestamp
cerebro-timezones
cerebro-weather
cerebro-wiki
convert-color
```

If that's the case, I think I need to go through the devtools and detect which plugin is causing this.

**Comment by KELiON** [comment]
@sepehr ok, I found! It is covert-color, I've opened an [issue in the repo](https://github.com/rafa-acioly/cerebro-convertcolor/issues/4), so this one can be closed

**Comment by rafa-acioly** [comment]
Hi guys, the problem was that I was using `bulma css` and I did not realize that the framework was overwriting the default style, sorry!

[the commit fixing the problem](https://github.com/rafa-acioly/cerebro-convertcolor/commit/9c8a830dbfc034318540cc69f97e634df877b697)

**Comment by KELiON** [comment]
@rafa-acioly it was fast! Thank you!:)

**Comment by sepehr** [comment]
Thank you @KELiON and @rafa-acioly both for finding and fixing this. 

@rafa-acioly BTW, I was used to the font family change, that was way nicer than the default font face.
