### ISSUE TITLE
Single key launch

### ISSUE THREAD

**Issue by navdeepio** [KELiON/cerebro#270]
Hi,

I'm using the latest cerebro version on archlinux(gnome). I'd love to map the `Super` key to quickly launch cerebro- is that possible? Trying to set a shortcut via config or the settings menu didn't work.

**Comment by KELiON** [comment]
@navdeepio hey! In UI you can set only keys with modifiers (so, you can't set single key). When you edited config, did you try to restart? It should work, if OS doesn't limit this usage somehow. What OS/version do you use?

**Comment by navdeepio** [comment]
@KELiON Hi, I tried to restart but got this error

`Uncaught Exception:
TypeError: Error processing argument at index 0, conversion failure from Super
    at TypeError (native)
    at exports.default (/usr/lib/cerebro/resources/app.asar/main.js:231:29)
    at App._electron.app.on (/usr/lib/cerebro/resources/app.asar/main.js:99:44)
    at emitTwo (events.js:111:20)
    at App.emit (events.js:191:7)`

**Comment by KELiON** [comment]
@navdeepio I've tried to test it on my machine and looks like it is not possible to register global shortcut with Electron, that uses only modifier key. So, along with modifier should be defined another key with `+`. I'll check later source code to be sure:)
