### ISSUE TITLE
Drag and Select.

### ISSUE THREAD

**Issue by h4ndshake** [KELiON/cerebro#272]
Hi, i've found some weird behaviour on Cerebro.
1. There are situations where the user can Select All html elements inside the app (Ctrl + A)
2. Users can drag Cerebro window around (probably an unwanted case?)

These two issues can be resolved with the following css properties
`-webkit-app-region: no-drag;`
`-webkit-user-select: none;`

**Comment by Kageetai** [comment]
2. is definitely a wanted feature :)

**Comment by h4ndshake** [comment]
So.. since it's a wanted feature, I will close this issue now.
Cheers.
