### ISSUE TITLE
[Bug] Issue with preview icons displaying on Windows 10

### ISSUE THREAD

**Issue by AlexAlabyev** [KELiON/cerebro#274]
- [x] I am on the [latest](https://github.com/KELiON/cerebro/releases/latest) Cerebro.app version
- [x] I have searched the [issues](https://github.com/KELiON/cerebro/issues) of this repo and believe that this is not a duplicate

- **OS version and name**:  Windows 10
- **Cerebro.app version**: 0.2.8
- **Relevant information from devtools**:  

## Issue

 There's no app image in the **details area**

![screenshot 1111](https://cloud.githubusercontent.com/assets/13764106/24840114/d29ad1e6-1d6f-11e7-8153-de67641f09ce.png)

**Comment by KELiON** [comment]
Hey, @SkaceKamen, can you please check it?

**Comment by SkaceKamen** [comment]
The issue is that while the results list uses the `SmartIcon` element, the preview just uses `img`, which doesn't trigger the icon loader.
Replacing the icon element in basic-app with `SmartIcon` works.

**Comment by SkaceKamen** [comment]
I can create PR if you wish, it's just one line change.

**Comment by tonymorello** [comment]
@SkaceKamen I have the same issue on W10... If you can create the PR it would be great!
