### ISSUE TITLE
Download link format changed - brew cask install fail

### ISSUE THREAD

**Issue by janclarin** [KELiON/cerebro#279]
There was a change in the version tagging. This results in `brew cask install cerebro` failing due to the download link changes. I have created a [pull request in brew cask](https://github.com/caskroom/homebrew-cask/pull/32172) to resolve this if this is intended. This needs to be consistent for future versions.

In 0.2.7, this was the download link (which was consistent with previous releases):
https://github.com/KELiON/cerebro/releases/download/0.2.7/cerebro-0.2.7.dmg

In 0.2.8, the download link in releases became (note the **v** before 0.2.8):
https://github.com/KELiON/cerebro/releases/download/v0.2.8/cerebro-0.2.8.dmg

This needs to be consistent to prevent brew cask from failing or having to be updated constantly.

**Here is the [download link being used in homebrew cask](https://github.com/caskroom/homebrew-cask/blob/master/Casks/cerebro.rb#L6)** which matches the links prior to 0.2.8 (i.e. there was no **v** prefix).

- [x] I am on the [latest](https://github.com/KELiON/cerebro/releases/latest) Cerebro.app version
- [x] I have searched the [issues](https://github.com/KELiON/cerebro/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: macOS Sierra 10.12.4
- **Cerebro.app version**: 0.2.8
- **Relevant information from devtools** _(See above how to open it)_: N/A

**Comment by KELiON** [comment]
Thanks for this fix, @janclarin! Now it should be consistent and always with "v" prefix. Reason for this change was that autocompete stopped to work without this prefix

**Comment by janclarin** [comment]
Okay, glad to hear that. No problem, @KELiON!
