### ISSUE TITLE
Extracting main UI elements to cerebro-ui package

### ISSUE THREAD

**Issue by KELiON** [KELiON/cerebro#282]
I started discussion in #277  and most of the plugin contributors agreed in #280 that it is important to have common UI components as a standalone package for easy reusability.

I've already create repository for that: https://github.com/KELiON/cerebro-ui

Here I'd like to track the progress and discussion.

As I see now, this package should include:

* Form elements (checkbox, text input, radio button, dropdown, labels)
* Loader
* List with keyboard navigation (like in google preview now)
* (ideas what else?)

**Comment by ocReaper** [comment]
A grid or layout system would be nice, since many plugin use 2 column layout with an image and a description. Also a card-like element could be useful like the one in the [brainmaestro/cerebro-stackoverflow](https://github.com/brainmaestro/cerebro-stackoverflow) plugin.

**Comment by lubien** [comment]
I think we should learn from mature UI frameworks like Quasar.

Let's take a look at [Quasar's list view](http://quasar-framework.org/quasar-play/android/index.html#/showcase/css/list/basic).

Pretty much covers a lot of common cases in list views like simple lists, lists with icons (at left, right or both sides), lists with dropdown buttons, lists with images...

The [Card element](http://quasar-framework.org/quasar-play/android/index.html#/showcase/css/card/basic) is always useful.

[Tabs](http://quasar-framework.org/quasar-play/android/index.html#/showcase/layout/tabs) would be great, specially in contexts like settings.

And other minor UI components like form inputs or labels would make the plugin development experience easier :)

**Comment by KELiON** [comment]
We can move this conversation to [cerebro-ui](https://github.com/KELiON/cerebro-ui) repo. Currently I didn't add new components, just moved what was already implemented.
