### ISSUE TITLE
Does not work when spotlight is disabled

### ISSUE THREAD

**Issue by jrop** [KELiON/cerebro#286]
- [x] I am on the [latest](https://github.com/KELiON/cerebro/releases/latest) Cerebro.app version
- [x] I have searched the [issues](https://github.com/KELiON/cerebro/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: macOS Sierra 10.12.2
- **Cerebro.app version**: 0.2.8
- **Relevant information from devtools** _(See above how to open it)_: N/A

## Issue
First of all, thanks for an awesome app!  I now use Cerebro exclusively instead of Spotlight.

Recently, I had to disable Spotlight because indexing was slowing my PC to a crawl.  I disabled it like so:
```sh
$ sudo mdutil -i off /
```
This means that on OSX, Cerebro is rendered ineffective for opening apps, as it uses `mdfind` to query for them (plugins still work, though).  It would be nice if there was a fallback to the linux-like app-finder (as implemented in `app/main/plugins/core/basic-apps/linux.js`) that could start searches in the following locations:

* /Applications
* /Users/{current-user}/Applications

Thanks!

**Comment by KELiON** [comment]
@jrop I was waiting for this issue and expected that someone turns off spotlight indexing :D 

It absolutely makes sense to do it and should not be hard to implement. Thanks for reporting it!

**Comment by KELiON** [comment]
@jrop finally I released version 0.3.0, where you can disable mac apps plugin and install basic apps, that will work without spotlight index.

**Comment by jrop** [comment]
Awesome; confirmed working.  Thanks again!
