### ISSUE TITLE
No autostart?

### ISSUE THREAD

**Issue by dragGH102** [KELiON/cerebro#290]
I love the package! (running on Debian 8.5)

However I find a bit frustrating it can't run on system startup.
Is there a way?

Also, no shortcut for quick toggle (rather than right click -> Toogle)?

Thank you

**Comment by FedoraTipper** [comment]
Download tweak tool, and add it to system start up. That's if you running gnome stack, there are other ways to run for another DEs.

**Comment by dragGH102** [comment]
@FedoraTipper thanks.

> Also, no shortcut for quick toggle (rather than right click -> Toogle)?

**Comment by renesansz** [comment]
To add it to your system startup you just have to do the following:
1. Go to "System Preferences"
2. Go to "Users & Groups"
3. Unlock the settings first then go to "Login Items".
4. Click the "+" sign and add the Cerebro.app
5. Done

**Comment by dragGH102** [comment]
@renesansz thanks for your step-to-step instructions. however I still don't get how can I toggle Cerebro without right click on the tray icon :)

**Comment by KELiON** [comment]
@dragGH102 there is a global shortcut (<kbd>ctrl+space</kbd> by default). You can change it using tray icon -> preferences
