### ISSUE TITLE
Cannot open Cerebro on a full-screen application

### ISSUE THREAD

**Issue by renesansz** [KELiON/cerebro#293]
- [x] I am on the [latest](https://github.com/KELiON/cerebro/releases/latest) Cerebro.app version
- [x] I have searched the [issues](https://github.com/KELiON/cerebro/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: MacOS 10.12.5
- **Cerebro.app version**: 0.2.7

## Issue
Cannot open Cerebro (using shortcuy key) when you are on a full-screen application (eg: Safari on full-screen).

Steps To Reproduce:
1. Open any MacOS application (Make sure Cerebro is running)
2. Full-screen the app (⌃+⌘+F shortcut)
3. Trigger Cerebro (⌃+Space)

Expected Result:
**Cerebro search should appear just like how Spotlight search can be triggered.**

**Comment by KELiON** [comment]
@renesansz I can't reproduce it( Can you attach gif/video?

**Comment by renesansz** [comment]
@KELiON After system restart it seems it works as expected now. I'll close the issue now.
