### ISSUE TITLE
InitializeAsync not working in plugin

### ISSUE THREAD

**Issue by jrjohnson1231** [KELiON/cerebro#294]
- [x] I am on the [latest](https://github.com/KELiON/cerebro/releases/latest) Cerebro.app version
- [x] I have searched the [issues](https://github.com/KELiON/cerebro/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: Ubuntu 16.04
- **Cerebro.app version**: 0.2.7

## Issue
I can not get the example plugin for intitializeAsync https://github.com/KELiON/cerebro/blob/master/docs/plugins/examples.md to work. Here is my modified code:

    let data = [];

    const fetchYourData = () => {
      return Promise.resolve(['hello, world'])
    }
    
    // Run some long-running initialization process in background
    const initialize = (cb) => {
      fetchYourData().then(cb);
      // and re-fetch this information once in 1h
      setInterval(() => {
        initialize(cb);
      }, 60 * 3600);
    }
    
    const onMessage = (results) => {
      console.log('results', results);
      data = results;
    }
    
    const plugin = (scope) => {
      scope.display(data);
    }

    module.exports = {
      initializeAsync: initialize,
      onMessage: onMessage,
      fn: plugin
    }

It would appear that the initialize function never gets entered. I have added console.log statements in intitialize and onMessage but they never show.

**Comment by KELiON** [comment]
@jrjohnson1231 hey! I could reproduce this issue and looks like it is related to race condition, so we try to run `initializeAsync` before background process is ready for it. I'll fix it. 

Currently to debug your problem you can load application, run `npm run debug` in your plugin directory. It will load plugin code, but to run `initializeAsync` properly you need to reload main window (open dev. tools (main) and reload it). It works for me

**Comment by KELiON** [comment]
Now all issues related to race condition here a fixed
