### ISSUE TITLE
Separate plugins by OS

### ISSUE THREAD

**Issue by saimonmoore** [KELiON/cerebro#3]
Right now plugins are OS-ignorant and pretty hard coded for osx. Would be good to have a scheme where by the correct os-specific plugin is chosen for a certain feature

**Comment by KELiON** [comment]
@saimonmoore It is started in https://github.com/KELiON/cerebro/pull/12. You can test it on linux, it should work (but without applications/define/contacts plugins). 

I've also created several issues for full linux support: https://github.com/KELiON/cerebro/issues?q=is%3Aissue+is%3Aopen+label%3Alinux

**Comment by KELiON** [comment]
@saimonmoore starting from version [0.2.1](https://github.com/KELiON/cerebro/releases/tag/0.2.1) Linux and Windows are supported, we only need to add plugins to launch application there (#14, #15)
