### ISSUE TITLE
App icons not showing up in v0.2.8

### ISSUE THREAD

**Issue by ishaanverma** [KELiON/cerebro#301]
- [x] I am on the [latest](https://github.com/KELiON/cerebro/releases/latest) Cerebro.app version
- [x] I have searched the [issues](https://github.com/KELiON/cerebro/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: Windows 10
- **Cerebro.app version**: 0.2.8
- **Relevant information from devtools** _(See above how to open it)_: 

## Issue

The app icons are not showing up in windows 10 for any app. They are just showing broken links.

![image](https://cloud.githubusercontent.com/assets/18427417/25566679/65d49320-2dfb-11e7-81fa-10bf0a677042.png)

**Comment by KELiON** [comment]
@SkaceKamen do you have any idea why could it happen?

**Comment by SkaceKamen** [comment]
I'm not sure what could be causing it, it works on my system (windows 7 x64), so it's probably related to windows 10?

**Comment by maximbaz** [comment]
This is not my computer, but I got you a few of the relevant screenshots (Windows 10 x64). 
Notice duplicate entries for the same app, as well as missing icons.

![cerebro1](https://cloud.githubusercontent.com/assets/1177900/25861297/98076760-34e4-11e7-9368-92343180fbc8.PNG)

![cerebro2](https://cloud.githubusercontent.com/assets/1177900/25861299/9d5df9cc-34e4-11e7-8b02-91444c389cda.PNG)

**Comment by italolanza** [comment]
I am having the same problem on Windows 7 x64.
![captura de tela 2017-05-09 15 57 46](https://cloud.githubusercontent.com/assets/19929055/25867564/50c85b3e-34d0-11e7-83dc-2ef20a6e4677.png)

**Comment by a4orce84** [comment]
Hello,

I am also experiencing this issue.  My system information is below:

OS version and name: Windows 10
Cerebro.app version: 0.2.8

If you need any additional information to help in the troubleshooting process, please let me know.  Thank you in advance for all of your time and help, it is greatly appreciated!

Thanks,
Asif

**Comment by SkaceKamen** [comment]
Could you show me the console output for both the main and background? I'm interested in any errors shown.
By the details you've posted, it looks like the icon loader failed and decided to use the path instead, but I don't know how that happens neither am I able to replicate the issue.

**Comment by italolanza** [comment]
I do not have much experience with programming but i can try if you tell how. What do I need to do to get this outputs ?

**Comment by KELiON** [comment]
@italolanza steps to get output: 


* open cerebro preferences;
* turn on `developer mode`, `show in menu bar`
* in tray menu open development -> Dev. Tools (Main), Dev. Tools (background)
* In tray menu choose development -> reload

Check both developer tools windows in console tab. If you see any errors – attach screenshot/text from this tab

**Comment by italolanza** [comment]
@KELiON thanks for the explanation. Here some screenshots i made. If is needed more information just ask.
![captura de tela 2017-05-22 07 38 42](https://cloud.githubusercontent.com/assets/19929055/26305577/46d7a13e-3ec6-11e7-84da-38910bf63cbb.png)
![captura de tela 2017-05-22 07 52 56](https://cloud.githubusercontent.com/assets/19929055/26305580/4709e310-3ec6-11e7-8960-b2a92c419d3f.png)
![captura de tela 2017-05-22 07 58 34](https://cloud.githubusercontent.com/assets/19929055/26305579/47031ed6-3ec6-11e7-9f73-bbe1474d1564.png)

**Comment by SkaceKamen** [comment]
By the output, it looks like it tries to load the icon, but fails somehow, but instead of reporting error, it just returns empty data.
I found this: https://github.com/electron/electron/issues/8767
Is it possible you have non-standard DPI?

**Comment by SkaceKamen** [comment]
OK, I just replicated the issue by changing DPI. @KELiON updating the electron should solve the issue, I'm unsure if the fix is in the latest release of electron.

**Comment by KELiON** [comment]
Just to make sure, can you try to execute one piece of code, @italolanza? For that you can open Dev. tools (main) (using instructions above) and copy-paste this code to console (but make sure you replace `/Applications/1Password.app` with absolute path for file, that doesn't show icon in Cerebro now:

```
require('electron').remote.app.getFileIcon('/Applications/1Password.app', (err, icon) => {
  if (err) {
    console.log('error', err)
  } else {
    console.log(icon.toDataURL())
  }
})
```

In my case (when it works) it shows this:

<img width="1067" alt="screen shot 2017-05-23 at 10 31 25" src="https://cloud.githubusercontent.com/assets/594298/26345480/518c3012-3fa3-11e7-8152-7fb0a730d37e.png">

**Comment by maximbaz** [comment]
There you go for that Windows laptop I mentioned earlier. And yes, it has a HiDPI screen.

![screenshot](https://cloud.githubusercontent.com/assets/1177900/26346386/5263b322-3fa6-11e7-92c4-ee67eec7ef2c.png)

**Comment by a4orce84** [comment]
Hello Everyone,


I apologize for joining late to this discussion.  Has there been a solution identified that we can test out?



Thanks again for everyone's work on this, it is greatly appreciated!

________________________________

**Comment by KELiON** [comment]
@a4orce84 hey! Not yet – we're going to update electron in next release, it should fix the problem

**Comment by italolanza** [comment]
@KELiON, sorry for the delay. Just to confirm what @SkaceKamen said, here in my computer I use the DPI set in 125%. When I changed it back to 100% the icons started to show up. Here the screenshots that you asked. 

With the DPI set in 125%:

![captura de tela 2017-05-23 18 09 27](https://cloud.githubusercontent.com/assets/19929055/26376839/59e262d6-3fe4-11e7-8077-4a585b9f4916.png)

![captura de tela 2017-05-23 18 11 08](https://cloud.githubusercontent.com/assets/19929055/26376840/59fe7af2-3fe4-11e7-92eb-f8cf02c54be7.png)

With the DPI set in 100%:

![captura de tela 2017-05-23 15 04 38](https://cloud.githubusercontent.com/assets/19929055/26376900/94f62b50-3fe4-11e7-9dcc-a34fbf806514.png)

![captura de tela 2017-05-23 15 03 32](https://cloud.githubusercontent.com/assets/19929055/26376906/9c4fc186-3fe4-11e7-99ed-0427aa4fd645.png)

**Comment by SkaceKamen** [comment]
Just to clarify, the icon not working in preview (in both cases) is fixed in https://github.com/KELiON/cerebro/pull/276

**Comment by italolanza** [comment]
Nice! If it is necessary I am available for testing on Windows again. Thanks!

**Comment by a4orce84** [comment]
When is the new version with the fix being released approximately?  Thanks.

________________________________

**Comment by KELiON** [comment]
Can someone check if it is fixed in the latest version?

**Comment by gluons** [comment]
It work! 🎉 

![1](https://user-images.githubusercontent.com/4688092/27027705-a93f6b00-4f8c-11e7-893f-ca06588b7777.png)

**Comment by sepehrHosseini** [comment]
It worked after updating to [0.3.0](https://github.com/KELiON/cerebro/releases/tag/v0.3.0) but the icon is small 32x32. It would be a lot better if it was larger! Is it possible ?
