### ISSUE TITLE
Search files on pc and google drive, dropbox,..

### ISSUE THREAD

**Issue by Hoolite** [KELiON/cerebro#303]
Hi,

I'm looking for an alternative app which makes it easy to find and locate files on my pc by a simple search. For example I want to find an excel file on my Google Drive, how can I use this app to find that file?

It doens't seem to find any file, not even located on my desktop.

Please help,

Kind regards,

**Comment by KELiON** [comment]
Hey! Currently you can search only in specified location, i.e. you can type `~/Google Drive/` to start searching in `Google Drive` folder in your userpath, but it currently searchs only in root level of the directory. You can get more info in #115

**Comment by rlech** [comment]
it should search the whole system. on osx with spotlight its supereasy to open a file by just typing its name into spotlight or Alfred
