### ISSUE TITLE
only search for web , doesn't search locally at all

### ISSUE THREAD

**Issue by ahmedMostafa-cg** [KELiON/cerebro#305]
- [x] I am on the [latest](https://github.com/KELiON/cerebro/releases/latest) Cerebro.app version
- [x] I have searched the [issues](https://github.com/KELiON/cerebro/issues) of this repo and believe that this is not a duplicate

- **OS version and name ubuntu 16.4**: 
- **Cerebro.app version 2.8**: 
- **Relevant information from devtools** _(See above how to open it)_: 

## Issue

i tried to search for local files and it doesn't work at all i searched online for solution but i didn't met any thing that could help me , any thing i type it give me the search web option .

**Comment by joseph-zhong** [comment]
I'm on Ubuntu 16.04 and it seems as though the only way to search for local files is to type the full path starting from `~/Downloads/...`

Is there a way to search without having to type the beginning?

**Comment by KELiON** [comment]
Duplicate #115
