### ISSUE TITLE
Appears off-screen when in full-screen view on macOS

### ISSUE THREAD

**Issue by clhynfield** [KELiON/cerebro#323]
- [x] I am on the [latest](https://github.com/KELiON/cerebro/releases/latest) Cerebro.app version
- [x] I have searched the [issues](https://github.com/KELiON/cerebro/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: macOS Sierra 10.12.4 (16E195)
- **Cerebro.app version**: 0.2.8
- **Relevant information from devtools** _(See above how to open it)_: 

## Issue

When I toggle Cerebro while in full-screen view, the Cerebro window appears off-screen, I think maybe on the last non-full-screen space: 

![cerebro-mac-fullscreen](https://cloud.githubusercontent.com/assets/148868/26510856/35972aba-422d-11e7-9ef6-fbcc3c43a7f9.gif)

**Comment by KELiON** [comment]
@clhynfield hey! Trying to reproduce it but have no success and for me it works well. Can you give more details and answer next question?

1) Is it your first start of Cerebro? 
2) Did you move Cerebro window? 
3) Do you have external displays?
4) Can you copy and paste here `positions` key from config file? You can execute this command in Terminal to do it: `cat ~/Library/Application\ Support/Cerebro/config.json | grep positions -A 15`

**Comment by clhynfield** [comment]
@KELiON, thanks very much for the quick response! That first question led me to resolution – it *was* the first time I'd started Cerebro. I simply quit and restarted the app, and now it's appearing overtop apps in full-screen view. I'm answering your questions below in case it's helpful. 

1. Yes, it was my first start of Cerebro
2. No, I hadn't moved the Cerebro window
3. No, I didn't have any external display connected
4. Here you go: 
```shell-history
❯ cat ~/Library/Application\ Support/Cerebro/config.json | jq '.positions' 
```
```json
{
  "2077750269": [
    515,
    232
  ]
}
```
