### ISSUE TITLE
Hope support double option key click to active cerebro

### ISSUE THREAD

**Issue by leafonsword** [KELiON/cerebro#329]
It seems cerebro only support one time key clicking key binding,so I set 'option+space' to active;And I think double clicking is more fast,hoping support ~

**Comment by KELiON** [comment]
@leafonsword currently Cerebro can support only shortucts, available by electron. Spec for this kind of shortcuts is [here](https://github.com/electron/electron/blob/master/docs/api/accelerator.md). Currently there is no way to use double click as shortcut, only combinations of buttons with modifiers (alt, ctrl, cmd, shift)
