### ISSUE TITLE
Start position on two monitor systems

### ISSUE THREAD

**Issue by wstarcev** [KELiON/cerebro#33]
Expect to see search line in active monitor instead of 
![2017-01-26 15-19-23](https://cloud.githubusercontent.com/assets/668635/22331142/e233d612-e3da-11e6-9abb-18d8a23dd840.png)

**Comment by wstarcev** [comment]
![2017-01-26 15-21-41](https://cloud.githubusercontent.com/assets/668635/22331196/30813102-e3db-11e6-92b2-33fca7abfd64.png)
![2017-01-26 15-21-47](https://cloud.githubusercontent.com/assets/668635/22331195/30805a7a-e3db-11e6-849d-5cb455241ea4.png)

**Comment by KELiON** [comment]
Merging it into #35
