### ISSUE TITLE
Cerebro didn't show app immediately after install ~

### ISSUE THREAD

**Issue by leafonsword** [KELiON/cerebro#331]
- [x] I am on the [latest](https://github.com/KELiON/cerebro/releases/latest) Cerebro.app version
- [x] I have searched the [issues](https://github.com/KELiON/cerebro/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: 
- **Cerebro.app version**: 
- **Relevant information from devtools** _(See above how to open it)_:

**Comment by KELiON** [comment]
Sorry, we can't solve issues with 0 details ;)
