### ISSUE TITLE
How could I disable Google search?

### ISSUE THREAD

**Issue by nazar-pc** [KELiON/cerebro#333]
I'm using Cerebro as apps launcher and never want to use it for web search. However, sometimes I end up executing search queries which I don't want to do, especially considering it is a Google search (my search engine of choice is Duckduckgo).

I can't find corresponding plugin and do not see an option to disable this. I remember you've being planning to decouple everything into plugins, will it be possible to disable/remove search entirely then?

**Comment by danielmelogpi** [comment]
It would be nice to have google search as a plugin so we could have more flexibility

**Comment by maximbaz** [comment]
It is already extracted from the main repository [as a separate plugin](https://github.com/KELiON/cerebro-google), so we are all eagerly awaiting the 0.2.9 release to finally be able to disable it 🙂

**Comment by danielmelogpi** [comment]
I see.
It seems that the same applies to Yandex translate:
https://github.com/KELiON/cerebro-yandex-translate

**Comment by KELiON** [comment]
Yes, I've finished extracting plugins, but there are few minor bugs that prevents from releasing it:) But it will be soon, I promise! :D

**Comment by KELiON** [comment]
In [version 0.3.0](https://github.com/KELiON/cerebro/releases/tag/v0.3.0) you can uninstall google plugin as any other
