### ISSUE TITLE
Cerebro does not show up in full-screen mode on Mac

### ISSUE THREAD

**Issue by timurkhafizov** [KELiON/cerebro#34]
When I toggle Cerebro in full-screen mode search window shows up on Desktop instead of current window.

It is expected to have search window on the top of current application like Spotlight does.
Is it relatively easy fix?

I would like to help if you can point me to the code I can start my investigations from.

**Comment by timurkhafizov** [comment]
Seems problem solved after restart.

**Comment by stevemao** [comment]
It doesn't work when I fullscreen my chrome. Alfred would show up on top of the fullscreen browser.
