### ISSUE TITLE
Hotkey in combination with text editors with same hotkey for autocomplete

### ISSUE THREAD

**Issue by arabron** [KELiON/cerebro#343]
- [x ] I am on the [latest](https://github.com/KELiON/cerebro/releases/latest) Cerebro.app version
- [x ] I have searched the [issues](https://github.com/KELiON/cerebro/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: Windows 10 
- **Cerebro.app version**: 0.27 
- **Relevant information from devtools** _(See above how to open it)_: 

## Issue

I know that we have option for changing hotkey but when u try to use some text editor/IDE that have autocomplete function (same hotkey as cerebro app ) cerebro instantly launch. You should consider adding function so when you are in some program that use same hotkey as cerebro if you just press that hotkey it dont launch app but if you hold hotkey (2 sec ) it work normal.

**Comment by KELiON** [comment]
From technical perspective, it is not possible to track if hotkey was used by other program. Only one option is when this hotkey event stopped/preveted by this program. I.e. if <kbd>ctrl+space</kbd> bound for Spotlight on MacOS and Cerebro uses the same hotkey, Cerebro never knows that this hotkey is used.
