### ISSUE TITLE
Round border and shadow missing in Lubuntu

### ISSUE THREAD

**Issue by RodrigoHamuy** [KELiON/cerebro#346]
Hi Guys, thanks for this amazing app. What should I do to get the round border and shadow like here?

This is how mine looks:
![2017-06-15-204259_650x45_scrot](https://user-images.githubusercontent.com/2405611/27198729-4e10c72a-520b-11e7-9ade-3c26c5f096aa.png)

How it should look:
![image](https://user-images.githubusercontent.com/2405611/27198761-6aeb9758-520b-11e7-8ee8-74a98e5791eb.png)

Thanks

**Comment by KELiON** [comment]
@RodrigoHamuy hey! Can you do a bigger screenshot, please?

> How it should look:

Actually, it shouldn't look like this, because it depends on operation system. It have small differences in MacOS, Linux and Windows

**Comment by maximbaz** [comment]
@RodrigoHamuy the system is responsible for drawing borders and shades. Have a look at some composition settings in Lubuntu, there must be something about it.

I'm on ArchLinux with compton running for composition. I don't know what Lubuntu uses, but it must use something for composition - if anything you can try compton as well 🙂

-----

This is how Cerebro works on Linux without any composition enabled at all (this is unusual):

![image](https://user-images.githubusercontent.com/1177900/27238045-a9796f3e-52cb-11e7-8c5b-a06fec10842a.png)

Normally I ask compton to darken background behind the active window:

![image](https://user-images.githubusercontent.com/1177900/27238026-9a080cae-52cb-11e7-9afc-9d784d009623.png)

Looks even nicer with Dark theme 🙂

![image](https://user-images.githubusercontent.com/1177900/27238118-fa150d5e-52cb-11e7-9251-dfdc38a49f24.png)

I can also enable shadow in the composition settings if I choose to, the position and size of the shadow is adjustable:

![image](https://user-images.githubusercontent.com/1177900/27238293-9725a78e-52cc-11e7-8e83-41ba884c1b5f.png)

----

Related: #81

**Comment by RodrigoHamuy** [comment]
Thanks, guys, I may play with compton on Lubuntu later... for now, I am happy just switching to the dark theme.
