### ISSUE TITLE
Calculator copy broken

### ISSUE THREAD

**Issue by Jantje19** [KELiON/cerebro#349]
When you press enter when you are done with the calculation it copies the word 'event' to your keyboard instead of the answer.

**Comment by KELiON** [comment]
@Jantje19 are you sure you didn't have `event` text in your clipboard before? <kbd>enter</kbd> just does nothing, you can copy result of calculation with <kbd>cmd/ctrl+c</kbd>

**Comment by Jantje19** [comment]
Sorry, I am dumb
