### ISSUE TITLE
Temporary disable of global shortcut

### ISSUE THREAD

**Issue by Jederalke** [KELiON/cerebro#351]
I'm making this feature request simply because I want to have something like I have mentioned in title. Basically you would have in context menu another menu called "Disable global shortcut for" and then some times(?) like 15 minutes, 30 minutes, 1 hour etc. and custom.

**Comment by KELiON** [comment]
Looks like super specific usecase. I see two solutions – turn off an application for this time or temporary change hotkey (i.e. you can use something complex, like cmd+ctrl+alt+shift+something)
