### ISSUE TITLE
Cannot bind control-\ (control backslash) to launcher

### ISSUE THREAD

**Issue by slippycheeze** [KELiON/cerebro#355]
- [x] I am on the [latest](https://github.com/KELiON/cerebro/releases/latest) Cerebro.app version
- [x] I have searched the [issues](https://github.com/KELiON/cerebro/issues) of this repo and believe that this is not a duplicate

- **Cerebro.app version**: 0.3 release
- **Relevant information from devtools** _(See above how to open it)_: N/A

## Issue
On macOS I bind Alfred to control-backslash (control-\), which works really nicely.  It's easy to hit, out of the way, and very efficient for me.  Unfortunately, experimenting with Cerebro, it doesn't permit that binding -- though control-shift-backslash (aka control-pipe / control-|) does work.

It would be great, from my perspective, if this were supported on all platforms; I'm on Windows when it happens, and have not verified other platforms, but since there is absolutely no reaction from the key binding control when I hit the sequence, my expectation is that it's not currently possible anywhere.

**Comment by KELiON** [comment]
@slippycheeze fixing it in #357, will be in next update

**Comment by KELiON** [comment]
Will be included in next release!
