### ISSUE TITLE
Order of search plugins

### ISSUE THREAD

**Issue by Taskkill** [KELiON/cerebro#359]
- [x] I am on the [latest](https://github.com/KELiON/cerebro/releases/latest) Cerebro.app version
- [x] I have searched the [issues](https://github.com/KELiON/cerebro/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: Linux Debian Stretch
- **Cerebro.app version**: 
- **Relevant information from devtools** _(See above how to open it)_: 

## Issue

Hello,
I would like to find a way to manage order of my search plugins. When I installed github search plugin it automatically became first search plugin, but I would like to Google search plugin to be the first one. I even tried to reinstall G search plugins hoping it will make it latest/preferred.  In Details about G search plugin there is gif and there IS G search before github search. I tried searching in issues but failed to find anything. Thanks for your work, I love this app.

**Comment by KELiON** [comment]
Hey, @tenorz007 what do you think about this one? Can we change `order` key for github plugin so it is moved below google result?

**Comment by tenorz007** [comment]
@KELiON I was planning to do that but just haven't gotten around to it. I should have that updated by today.

**Comment by Taskkill** [comment]
Cool, this solves my problem I guess, thank you.

**Comment by tenorz007** [comment]
@KELiON @Taskkill I have updated the plugin with some fixes too. It shouldn't show up ahead of the google plugin

**Comment by Taskkill** [comment]
@tenorz007 It's working like a charm! Thank you a lot for your help.

**Comment by tenorz007** [comment]
@Taskkill Glad I could help, I hope the plugin turns out to be useful to you!

**Comment by Taskkill** [comment]
@tenorz007 It indeed is.

**Comment by livejamie** [comment]
Is there a way to do the same for other plugins? I'd like to have Google Appear above the Everything plugin

https://github.com/masterperas/es-everything-plugin
