### ISSUE TITLE
Windows 10 не ищет приложения из Store

### ISSUE THREAD

**Issue by VladimirGr** [KELiON/cerebro#360]
- [x ] I am on the [latest](https://github.com/KELiON/cerebro/releases/latest) Cerebro.app version
- [ x] I have searched the [issues](https://github.com/KELiON/cerebro/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: Windows 10
- **Cerebro.app version**: 0.3.0
- **Relevant information from devtools** _(See above how to open it)_: 

## Issue

Ребята,привет! Очень нравится ваше приложение, но есть проблема. В Windows 10 не выдает при поиске приложения из магазина и стандартные приложения, например:
calc
skype

**Comment by KELiON** [comment]
Duplicate #310
