### ISSUE TITLE
Permanent y-scrollbar

### ISSUE THREAD

**Issue by petrleocompel** [KELiON/cerebro#361]
- [x] I am on the [latest](https://github.com/KELiON/cerebro/releases/latest) Cerebro.app version
- [x] I have searched the [issues](https://github.com/KELiON/cerebro/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: Ubuntu 16.04
- **Cerebro.app version**: v0.3.0

## Issue
Permanent scroll bar on y. Problem is `overflow-y: scroll` on `html` element. 
See atached pics.

![snimek z 2017-07-10 21-56-36 png](https://user-images.githubusercontent.com/9423543/28037495-cb4a9fd6-65bb-11e7-8f2f-8279c5f17f02.png)
![snimek z 2017-07-10 21-56-40 png](https://user-images.githubusercontent.com/9423543/28037498-cd1ded7c-65bb-11e7-9a39-4ec2c59b04eb.png)

**Comment by brpaz** [comment]
Same issue on Linux Mint 18.2

**Comment by brpaz** [comment]
Well i found the origin of this problem. is from the minireset.css which is being included somewhere and render inline styles which take precedence over the css files like global.css.

The only workaround for now I found is too add an inline style to the end of index.html file like:
```
 <style>
      html {
        overflow-y: hidden;
      }
    </style>
```

**Comment by KELiON** [comment]
@brpaz can you find where it was included? I suppose some plugin added it. Would be better to ask plugin maintainer to remove it instead of hardcoding this style rule

**Comment by petrleocompel** [comment]
It was plugin related bug.
