### ISSUE TITLE
Mac keyboard symbols in use instead of Super, CTRL, ALT, etc... for Windows

### ISSUE THREAD

**Issue by TheRndCoder** [KELiON/cerebro#37]
![cerebro_2017-01-26_08-34-02](https://cloud.githubusercontent.com/assets/25141697/22334957/4d977fd2-e3a2-11e6-87aa-663a35370946.png)

On Windows, the symbols for Mac keyboard are still present and in use instead of ALT, CTRL, Super key, etc...

This could create confusion for new users that aren't familiar with Mac keyboards.

**Comment by KELiON** [comment]
@TheRndCoder agree! I'll work on that
