### ISSUE TITLE
focus issue

### ISSUE THREAD

**Issue by farfromrefug** [KELiON/cerebro#374]
* Macos Sierra

With the latest cerebro there are some focus issue.
When i activate cerebro and click on the window behind, cerebro does not hide itself.
It should. You can see another app based on electron that does it: [zazu](https://github.com/tinytacoteam/zazu)

Related to focus issue. The best example around is Alfred.
Some great things that alfred does:
- Alfred does not still the current window focus. Very easy to see as the current window status bar does not change color (going gray) when you activate Alfred
- Alfred does hide itself if you click on the menubar. Also very useful. 

What's bugging me with those issues is that i often end up with a Cerebro window that does not close when i expect it to. So i need to use it's shortcut again to close it.

I hope this can be fixed

**Comment by KELiON** [comment]
Hey, @farfromrefug! Cerebro should be hidden when you click outside of the application. There is only one case when we don't do it – when "Developer mode" turned on in preferences. It is done to prevent hiding Cerebro window, when user set focus to developer tools. Can you check your settings?

> Alfred does not still the current window focus.

Interesting case, but not clear. Can you describe an example when it can be useful? Anyway, when you open alfred and start typing – focus is in Alfred application, so I don't see how focused application can be used without hiding alfred.

**Comment by farfromrefug** [comment]
Yes thanks about the dev mode that was part of the issue for me ️:s 

Now about alfred, here is a simple  example.
Before the screenshots i am focused on the github comment box.
As you can see with alfred the box keeps focused while typing is actually redirected to alfred.
I think the idea is to make sure we don't "pause" any running activity in the focused window.
I am not sure it's such a big deal, but i discovered it as i was looking at understanding my other issue :s

<img width="1296" alt="screen shot 2017-08-03 at 19 07 15" src="https://user-images.githubusercontent.com/655344/28933935-4c02ae90-787f-11e7-85c3-47dd11c72332.png">
<img width="867" alt="screen shot 2017-08-03 at 19 08 04" src="https://user-images.githubusercontent.com/655344/28933936-4c06f8a6-787f-11e7-8d4e-0cd0f03b614a.png">

**Comment by KELiON** [comment]
@farfromrefug hm, I still don't see the usecase of this. I've just tried and I see that it works the same way in Spotlight (text cursor left in Chrome, but typing is "redirected" to spotlight). But anyway, typing, shortcuts and everything works only in search (spotlight/alfred) in this case, not in Chrome. But after hiding search window, focus is "restored" back to chrome in all applications (including Cerebro).

**Comment by maximbaz** [comment]
A use-case for preserving the focus at all times (vs stealing and restoring it) would be to interact with apps that have some logic in "focusOut" event on _their_ side (such as preload something / submit a form / save current input / etc). 

The most annoying behavior I've seen is an app that closes itself on focusOut (not Cerebro, I turned on "Developer mode" to avoid that 😛), which asks me something that I need to copy from Cerebro. While I'm in the middle of entering something, opening Cerebro steals the focus from that app and it closes itself cancelling everything I typed so far 😕

To be fair, I've never seen the described Alfted's / Spotlight's behavior in Linux, it is possible that this is something specific to macOS only.

**Comment by farfromrefug** [comment]
@maximbaz Yes you explained much better than me :D 
I have usecases where there is for example a popup showing data and you want to have that data shown while using cerebro. ONe example is 1password. Thought it does not work either with alfred :P Would be awesome!

But i understand it's not that needed of a feature for now. And i actually don't even know if we can do that with electron. From the current API, i don't see it.

I think we can close this issue but keep it in mind somewhere ;)
