### ISSUE TITLE
Plugin isn't listed as installed when developing

### ISSUE THREAD

**Issue by puyt** [KELiON/cerebro#376]
- [x] I am on the [latest](https://github.com/KELiON/cerebro/releases/latest) Cerebro.app version
- [x] I have searched the [issues](https://github.com/KELiON/cerebro/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: macOs Sierra 10.12.16
- **Cerebro.app version**: 0.3.0

## Issue
I've had this issue when developing my plugin but i've tested the same with a new test plugin.
I've followed the steps from here https://github.com/KELiON/create-cerebro-plugin

## Screenshot
<img width="1400" alt="screen shot 2017-08-04 at 20 11 56" src="https://user-images.githubusercontent.com/3668615/28981537-6fc81a6c-7952-11e7-8993-7d2e119409ae.png">

**Comment by KELiON** [comment]
Proposal: `create-cerebro-plugin` creates symlink for new plugin, but doesn't add it to `package.json` in plugins directory. Actually it is not installed, so I'd add new "development" section in plugins list in addition to "Installed" and "available.

**Comment by puyt** [comment]
Sounds good 👍
