### ISSUE TITLE
Command bypass to terminal with ">"

### ISSUE THREAD

**Issue by AlexAlabyev** [KELiON/cerebro#38]
Please consider implementing command bypass to terminal, so that when you type in something like:
`> cd desktop`
1. terminal (cmd.exe on windows) would open up and 
2. the code would get passed there 

It's a very helpful feature in [Wox ](https://github.com/Wox-launcher/Wox) which is an alternative to cerebro. 

- **an option** to prevent it from closing after command execution would be very handy, as well as
- **an option** to show the list of the recent commands

![111](https://cloud.githubusercontent.com/assets/13764106/22335159/96c14958-e3ee-11e6-98a3-a83afac748b2.PNG)

**Comment by KELiON** [comment]
@AlexAlabyev can you try [shell](https://github.com/KELiON/cerebro-shell) plugin? It should solve your problem, but it even shows results in preview:

![screen shot 2017-01-26 at 17 41 34](https://cloud.githubusercontent.com/assets/594298/22340735/be35669a-e3ee-11e6-8dbd-5be100789696.png)

**Comment by AlexAlabyev** [comment]
@KELiON sorry, I forgot to mention. I'm on windows. And symbol $ doesn't do anything, it just searches google 
![1](https://cloud.githubusercontent.com/assets/13764106/22341079/985c8112-e400-11e6-8753-969b239450c5.gif)

**Comment by KELiON** [comment]
@AlexAlabyev oh, ok, it is known issue. I'll try to fix it on windows!

**Comment by KELiON** [comment]
Reopened in [cerebro-shell](https://github.com/KELiON/cerebro-shell/issues/3) repository
