### ISSUE TITLE
[FR]separated core from UI

### ISSUE THREAD

**Issue by farfromrefug** [KELiON/cerebro#383]
I had a crazy idea. I recently switched to android and the first thing i was looking for was a "cerebro/spotlight" app on android. There is nothing like it from what i could find. Something like a widget that could for example convert as you type.

So i wondered if i could actually write one. And obviously i thought to myself why not use cerebro code?
Well actually i can. I develop mobile apps using a fork of a cross-platform framework called Titanium Mobile. It allows me to use JS code and most npm modules (non native ones).
So if the GUI was separated from the core in cerebro, then i could quite simply do that.

Do you think this would be feasible? I am willing to look at it if you agree with the basic idea.

**Comment by KELiON** [comment]
@farfromrefug it could be also possible with React native, but anyway without main desktop OS functions and plugins, oriented to desktop, Cerebro is nothing, so It doesn't make sense to reuse UI and much easier to write your own :) Of course, some parts could be reused, but I don't see the reason to separate UI.

**Comment by farfromrefug** [comment]
@KELiON Honestly weird answer, but i'll leave with it and may be fork Cerebro, or look at Zazu
THanks
