### ISSUE TITLE
Source code showing up on Google Search on load

### ISSUE THREAD

**Issue by ThinkDigitalRepair** [KELiON/cerebro#389]
- [X] I am on the [latest](https://github.com/KELiON/cerebro/releases/latest) Cerebro.app version
- [X] I have searched the [issues](https://github.com/KELiON/cerebro/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: Fedora 26
- **Cerebro.app version**: (0.3.1)
- **Relevant information from devtools** _(See above how to open it)_: Opened it, but not sure what information would be relevant.
## Issue

When opening a Google search page from Cerebro, A lot of source code shows up briefly before loading the page. This doesn't happen after refreshing or typing in the URL again. More information can be provided if necessary.
![screenshot from 2017-09-15 10-14-50](https://user-images.githubusercontent.com/23037821/30495384-a9b1bf0c-9a00-11e7-96bb-9dc5c8301b77.png)

**Comment by robbporto** [comment]
I came here to open an issue exactly about this.

+1!

**Comment by KELiON** [comment]
Thanks for the issue! I've updated [cerebro-google](https://github.com/KELiON/cerebro-google) plugin with fix, so you should have it automatically (or just uninstall/install google plugin if you want it faster)
