### ISSUE TITLE
[macos] invisible on fullscreen apps

### ISSUE THREAD

**Issue by neronmoon** [KELiON/cerebro#39]
Steps to reproduce on mac os sierra:
1) switch chrome (for example) to fullscreen mode
2) try to toggle cerebro
3) ???
4) switch to default workspace
5) cerebro is visible for second

**Comment by neronmoon** [comment]
Fixed after restart. Whaaaaat? Not sure it may be closed.

**Comment by KELiON** [comment]
I've tried to reproduce it several times but looks like it works well. Let's wait some time, maybe someone will have the same issue
