### ISSUE TITLE
Unable to use the Settings feature of the Plugin API

### ISSUE THREAD

**Issue by wolfika** [KELiON/cerebro#393]
First of all, thank you for this great project. Cerebro is a cool and handy thing to have!

---

- **OS version and name**: elementaryOS 0.4.1 (built on Ubuntu 16.04.3 LTS)
- **Cerebro.app version**: 0.3.0
- **Relevant information from devtools**: Nothing relevant really, just a few deprecation/warning notices, but I think it's related to the core, not my plugin

## Issue
I'm writing a plugin for Cerebro using the [documentation](https://github.com/KELiON/cerebro/blob/master/docs/plugins.md) available. I would like to declare a few settings in my plugin which let the user configure the plugin to their liking. I'm declaring my settings like this:

```
module.exports = {
  fn: ({term, display, actions, settings}) => {
    // My plugin logic here
  },
  settings: {
    apiKey: {
    label: 'apiKey',
      description: 'API key specific to your user account',
      type: 'string'
    },
    instanceUrl: {
      label: 'instanceUrl',
      description: 'Public base URL of your instance',
      type: 'string'
    }
  }
};
```

As far as I can tell, this is in accordance with the way outlined in the plugin API docs. However, when I run the plugin in dev mode (using `npm run start` and live reloading), the settings don't appear in Cerebro. To be completely honest, I'm not even sure if I'm looking for them in the right place; they should be amongst Cerebro's own settings, right? See screenshot [here](https://i.imgur.com/aZ6vaEI.png). Anyway, I couldn't manage to get the settings appear at all. Unfortunately, I haven't found an actual plugiun (apart from the docs snippet I copied) that facilitates the Settings feature of the Plugins API.

I tried reloading/restarting the Cerebro app several times, but it did not help. Some help would be appreciated. Thanks!

_This might or might not be related to the discussion at #280._

**Comment by KELiON** [comment]
@wolfika Hey! Thanks for your report – there was a bugfix for that, but I didn't release Cerebro for a while, so it wasn't fixed in production build:) You can check it in the latest version – 0.3.2. I just tried your code and it works, just type `plugins` and you'll see your development plugin on top of the list, where you can edit settings:

![screen shot 2017-12-05 at 12 40 11](https://user-images.githubusercontent.com/594298/33597633-77365e2c-d9b9-11e7-8458-9f5b343d0715.png)
