### ISSUE TITLE
just white line and icon in toolbar

### ISSUE THREAD

**Issue by tonkoshkurik** [KELiON/cerebro#4]
При запуске вижу только белую полосу и иконка в панеле инструментов. Ни настроки ни само приложение не рабоет.
Mac Book pro mid 2012 el capitan 
Node v7.0.0 && NPM 3.10.8

**Comment by KELiON** [comment]
@tonkoshkurik возможно что-то связано с El Capitan, т.к. я тестировал только на Sierra. Давайте попробуем так: [тут лежит](https://www.dropbox.com/s/j9t9eu4h5qwocxc/Cerebro.dmg?dl=0) билд с включенными Developer Tools, при открытии должно выглядеть как-то так:  

![](http://g.recordit.co/xDpDl0Vrmd.gif)

Можете переключить на console и скинуть ошибки, которые будут там?

Всю следующую неделю буду в отпуске, но по возвращении постараюсь починить. Спасибо за фидбек!
