### ISSUE TITLE
Plugin install : Doc

### ISSUE THREAD

**Issue by maxime1992** [KELiON/cerebro#40]
Hi ! This looks really awesome, thanks for this work !

I installed cerebro and I wanted to try some plugin but I couldn't find how to do that.

Can add few lines about that in the README ?

Or if it's really simple just reply to this issue but I think it might help others :)

Thanks

**Comment by maxime1992** [comment]
Sorry I didn't see 

![image](https://cloud.githubusercontent.com/assets/4950209/22371502/bedd460e-e497-11e6-85bb-a0bafb2c3c47.png)

...

**Comment by KELiON** [comment]
@maxime1992 anyway you are not the first one who couldn't find it after first look, so I'll try to do it easier
