### ISSUE TITLE
System tray, Preferences..., doesn't select Cerebro Settings

### ISSUE THREAD

**Issue by duianto** [KELiON/cerebro#404]
- [x] I am on the [latest](https://github.com/KELiON/cerebro/releases/latest) Cerebro.app version
- [x] I have searched the [issues](https://github.com/KELiON/cerebro/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: Microsoft Windows 10 Version 1607 (OS Build 14393.1770)
- **Cerebro.app version**: 0.3.1
- **Relevant information from devtools** N/A 

## Issue

Cerebro Settings does not get selected, when right mouse button clicking on the system tray icon, and choosing: `Preferences...`

![cerebro_2017-11-07_09-23-48](https://user-images.githubusercontent.com/13420573/32483717-790d3432-c39d-11e7-9ffd-c8e09972a048.png)

#### Possible solution
Search for `Cerebro Settings` instead of just `settings`.

**Comment by lawgsy** [comment]
Interesting conflict of names. Running Windows 10 with a different locale this works fine:
![](https://i.imgur.com/H3ZNY8u.png)

Looking into this now.
