### ISSUE TITLE
Show icons for applications and preferences on MacOS

### ISSUE THREAD

**Issue by lavir** [KELiON/cerebro#42]
Cerebro does not display icons for applications and preferences on MacOS

Probably the reason is in that the apps in MacOS are folders. In the `apps/index.js` uses `path` for icon which is in this case is dir. Real icon is bit deeper `AppName.app/Contents/Resources/*.icns `

**Comment by Kageetai** [comment]
Icons work perfectly fine for me. Can you add a screenshot or so to clarify?

**Comment by KELiON** [comment]
@lavir what icons do you mean? Can you attach a screenshot? For me preferences icons work well

![screen shot 2017-01-30 at 10 56 31](https://cloud.githubusercontent.com/assets/594298/22418803/d74c9b32-e6da-11e6-9f75-2795f44e0ea7.png)

**Comment by lavir** [comment]
The screenshot below
I would like notice that I launched Cerebro by `npm run dev`.
![screen shot 2017-01-30 at 15 33 35](https://cloud.githubusercontent.com/assets/1274746/22425687/fef1a194-e704-11e6-8acf-94553d46171a.png)

**Comment by KELiON** [comment]
@lavir and does it work when you launch precompiled .app file? 

Also, I believe there is something broken for you in background process:

1) Type settings and turn on developer mode, turn on "show in menu bar";
2) Toggle Cerebro window and from tray menu select development → dev tools (background), switch to `console` tab;
3) Reload everything (development → reload);
4) Try to find 'mouse' and check if you have any errors in console;

**Comment by lavir** [comment]
.app works fine.

in dev mode no
in the background process didn't notice any problem (at least in Console) only this
`bindings.js:83 Uncaught Error: Module version mismatch. Expected 50, got 48.`

and in main process
`localhost:3000/dist/main.bundle.js:3100 Warning: setState(...): Can only update a mounted or mounting component. This usually means you called setState() on an unmounted component. This is a no-op. Please check the code for the Preload component.`

in the terminal nothing interesting too.

**Comment by KELiON** [comment]
@lavir looks like in your dev environment native modules were built with wrong modules versions. Check item 2 [here](https://github.com/KELiON/cerebro#resolve-common-issues) to fix your problem

**Comment by lavir** [comment]
Yes, this solved my problem.
Thank you!
