### ISSUE TITLE
Question about Plugins and Persistence

### ISSUE THREAD

**Issue by FreaKzero** [KELiON/cerebro#427]
Hi there, 
Writing right now a few plugins and try to "behave" what the code belongs - so before im doing anything im looking into other plugins.

I saw that basically none of other plugin writers uses local or sessionstorage - is this some "intent" of the community ?

Also thought maybe implementing [nedb](https://github.com/louischatriot/nedb) into cerebro would be a wonderful idea for persistence in plugins (settings and stuff) ?

Thanks for reading guys.

**Comment by lawgsy** [comment]
Settings have already been implemented, at least to some extent, they just aren't documented very well yet.

See https://github.com/KELiON/cerebro/issues/385 (or head straight for the source of the [translate plugin](https://github.com/KELiON/cerebro-yandex-translate/blob/master/src/index.js) that uses settings).

As for other uses of local storage, what are you looking for exactly?

**Comment by KELiON** [comment]
@FreaKzero Cerebro works as node.js process, so you can use filesystem and lot of plugins do it to store some information, like cached data. 

Also I think that in renderer process you can access local/session store, because it is just a chromium process, but I never tried it

**Comment by FreaKzero** [comment]
I just thought "what if i just have 1 simple integeter counter addition to save" or for "storing a public api token" - it would be a little bit over extensive just for a JSON object with 1 Property only for my application which is using FILEIO when i could use localstorage for this (faster/token wouldnt be in a file but enclosed in the application, etc)

But the Settings thing helps me big out right now atleast what tokens belong - thanks for the hint

btw great project guys - looked a long time for a launcher which works on every OS the same and uses electron for easy writing plugins.
