### ISSUE TITLE
Create a team in Slack?

### ISSUE THREAD

**Issue by lavir** [KELiON/cerebro#43]
Will be nice to have a team in the Slack for discussing and syncs tasks/bug fixes.
Possible some other alternative (Gitter?) to the Slack, but I personally prefer the Slack :)

**Comment by dmitryTsatsarin** [comment]
https://gitter.im/KELiON-cerebro
created. But as for me, "issues" is much better

**Comment by lavir** [comment]
ok, issues so issues

**Comment by KELiON** [comment]
@lavir @dmitryTsatsarin issues are good for tracking everything in one place, but some chat is good for small questions. I like slack, but for open-source project, gitter works better, I suppose. At least, it doesn't clean history and you can search through all messages. 

So, let's use [gitter](https://gitter.im/KELiON-cerebro/Lobby) for that

**Comment by KELiON** [comment]
OR we can do slack community with http://slackarchive.io/.

**Comment by KELiON** [comment]
👍 here for slack

**Comment by KELiON** [comment]
👍 here for gitter

**Comment by KELiON** [comment]
Ok, finally gitter is a leader! https://gitter.im/KELiON-cerebro is official channel
