### ISSUE TITLE
visitor(...).screenview is not a function (tracking causes crash)

### ISSUE THREAD

**Issue by FreaKzero** [KELiON/cerebro#437]
- [x] I am on the [latest](https://github.com/KELiON/cerebro/releases/latest) Cerebro.app version
- [x] I have searched the [issues](https://github.com/KELiON/cerebro/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: MacOS 10.11.6 (`sw_vers -productVersion `)
- **Cerebro.app version**: 0.3.2
![image](https://user-images.githubusercontent.com/6339036/33809612-f6e89dbc-ddf9-11e7-90bd-f903db0d8232.png)

![image](https://user-images.githubusercontent.com/6339036/33809615-068ad1f4-ddfa-11e7-8262-9fd6feb58f31.png)

## Issue

Seems like this line here https://github.com/KELiON/cerebro/blob/16c40246a1f950f0d549d98aa5c81c90e4944343/app/lib/trackEvent.js#L31 brings cerebro on my macos to crash WHEN cerebro started 1 time with an external display plugged in on boot - and afterwards restarting it without the display plugged in and the config value `trackingEnabled` on true i will get the error messages seen above and cerebro wont start.

**For other people who are facing this problem:**
goto `~/Library/Application Support/Cerebro`, open `config.json` and set `trackingEnabled` to 'false'

**Comment by FreaKzero** [comment]
oh sorry .. close duplicate

**Comment by sanzoghenzo** [comment]
Hi,
I don't see the duplicate issue so I'm posting here.
I had the exact problem on my macbook pro, same os and cerebro versions, But at first launch without having any external display attached.
The workaround solved this.
Still, welcoming a new user with an unhandled exception is not a great thing ;)

**Comment by FreaKzero** [comment]
hi @sanzoghenzo ive wrote a temporary workaround for this issue here https://github.com/KELiON/cerebro/issues/434

Or use 3.0.1 instead

**Comment by odahcam** [comment]
Installed Cerebro today from the Ubuntu 19.04 store and the issue persists.

PS.: The workaround works.

**Comment by ericol** [comment]
I just installed Cerebro on a clean install of Debian 10 and the error is happening. It seems the problem is related to the multi monitor set up I have. [This solution](https://github.com/KELiON/cerebro/issues/434#issuecomment-352442792) also still works.
