### ISSUE TITLE
Persist search result

### ISSUE THREAD

**Issue by egoist** [KELiON/cerebro#44]
**current**:

the search result would be cleared after toggling cerebro with shortcut

**expected:**

result should not be cleared.

**Comment by lavir** [comment]
or like in Alfred press UP key to listing previous commands

**Comment by KELiON** [comment]
@lavir did you try it? Up key shows previous result now. Would you like to change it somehow? /cc @egoist

**Comment by egoist** [comment]
@lavir that would be neat but `Persist search result` sounds reasonable? it still requires pressing `up` to get previous result, maybe adding an option to enable `Persist search result`?

**Comment by KELiON** [comment]
@egoist am I right that you just don't want to clear search field when window hidden/shown and show the same results?

**Comment by egoist** [comment]
@KELiON yep

**Comment by KELiON** [comment]
@egoist I like idea of checkbox in preferences, adding it to task list!
