### ISSUE TITLE
File search in windows

### ISSUE THREAD

**Issue by harish095** [KELiON/cerebro#49]
Hello, I was looking for a better alternative for Alfred on windows. After trying all the available software, I liked Cerebro and [Wox Launcher](http://www.getwox.com/). But an important feature missing in Cerebro is system wide file search. Wox launcher has this feature by using [Everything](https://www.voidtools.com/) plugin. I suggest same can be done for Cerebro.

**Comment by KELiON** [comment]
in #45 you can find a link @reflog's version of [everything plugin](https://github.com/reflog/cerebro-plugin-everything) that is work-in-progress. So, you can wait some time or help him with development :)
