### ISSUE TITLE
Cann't search on Elementary OS

### ISSUE THREAD

**Issue by cuongw** [KELiON/cerebro#491]
- [x] I am on the [latest](https://github.com/KELiON/cerebro/releases/latest) Cerebro.app version
- [x] I have searched the [issues](https://github.com/KELiON/cerebro/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: Elementary OS 5.0
- **Cerebro.app version**: 0.3.2
- **Relevant information from devtools** _(See above how to open it)_: 

## Issue
Cann't search on Elementary OS 5.0.

**Comment by rahulrana-exe** [comment]
What is the problem exactly? I'm on eOS Juno working fine for me.

**Comment by cuongw** [comment]
![Screenshot from 2019-07-06 00 18 22](https://user-images.githubusercontent.com/34389409/64924962-4203c680-d814-11e9-93b1-f67196f8ab76.png)
This is my error!

**Comment by BenoitDuffez** [comment]
Duplicate of #434, see [this comment](https://github.com/KELiON/cerebro/issues/434#issuecomment-385143757) for a workaround.

**Comment by cuongw** [comment]
I closed this issue!
