### ISSUE TITLE
Add alternative search engines and translation services

### ISSUE THREAD

**Issue by Calinou** [KELiON/cerebro#50]
It looks like only Google search and Yandex translate are available right now. It'd be nice to have DuckDuckGo search as an option, for example.

**Comment by KELiON** [comment]
Duplicate of #32. @captainhook said that he will try to implement DuckDuckGo plugin, so you can ping or coordinate to help him

**Comment by BurningTreeC** [comment]
how about the option to simply define your search engine by url?
