### ISSUE TITLE
Missing apps

### ISSUE THREAD

**Issue by oskarkrawczyk** [KELiON/cerebro#52]
I sometimes see missing obvious apps in the search results, like this:

<img width="719" alt="screen shot 2017-01-30 at 09 01 09" src="https://cloud.githubusercontent.com/assets/34213/22415856/c7bee70c-e6ca-11e6-8159-2b77923e1f3c.png">

Obviously missing the actual `App Store.app` – only finding the prefpane.

**Comment by KELiON** [comment]
@oskarkrawczyk yep, app store is also missed for me. Do you have other examples? Going to fix it

**Comment by oskarkrawczyk** [comment]
@KELiON I thought I've seen this happening for other apps but I might have been wrong

**Comment by KELiON** [comment]
@oskarkrawczyk fixed in #54 and will be included in next version
