### ISSUE TITLE
Cant find any program on windows

### ISSUE THREAD

**Issue by StarpTech** [KELiON/cerebro#56]
"Spotify", "Slack" no app can be found when I type the exact name.

Windows 10
Cerebro: 0.2.3
No plugins installed

**Comment by KELiON** [comment]
Applications search currently works only on mac, you can check progress for windows in #15

**Comment by StarpTech** [comment]
@KELiON The references issue has nothing to do with windows

**Comment by KELiON** [comment]
@StarpTech oops, it had to be #14
