### ISSUE TITLE
It's not working on Linux VMs (VirtualBox) - shows white frame/square

### ISSUE THREAD

**Issue by jjnilton** [KELiON/cerebro#60]
It shows a white frame/tile when I open, does not show any UI. The VMs have 3D acceleration enabled, any idea what could be the issue?

![image](https://cloud.githubusercontent.com/assets/228200/22449571/c5fc315c-e73f-11e6-9bf9-ce49d533317e.png)

**Comment by KELiON** [comment]
@jjnilton what Linux distribution do you use?

**Comment by jjnilton** [comment]
@KELiON Ubuntu GNOME 16.04 host, tried guests: Xubuntu 16.04, Ubuntu MATE 16.04.

**Comment by maximbaz** [comment]
I've had that once too, killing all the `cerebro` processes helped (just make sure to kill _all of them_, there are many).

**Comment by jjnilton** [comment]
I tried to `killall cerebro` multiple times, but every time I run, it runs like this. Did you do it in a VM?

**Comment by maximbaz** [comment]
No, not on VM. 

Hm, I've just ran `killall cerebro` two times (apparently the first run doesn't kill all the processes :confused:), then started the app and I saw a white screen.

Two times `killall cerebro` again, and on the next run it's all good... weird.

**Comment by megamorphf** [comment]
there is a bug related virtual box and all other programs that use webkit in their stack (google chrome, atom etc... ). You can workaround this issue by following these steps:

1. locate `.desktop` file:  `/home/<username>/.local/share/applications/appimagekit-cerebro.desktop`
2. Edit `.desktop` file line: 
from:
```
Exec=/home/hermes/Downloads/cerebro-0.2.6-x86_64.AppImage %U
```
to:
```
Exec=/home/hermes/Downloads/cerebro-0.2.6-x86_64.AppImage %U --use-gl=angle
```

**Comment by KELiON** [comment]
@jjnilton  does fix by @megamorphf work for you?

**Comment by megamorphf** [comment]
yes it does you can also use parameter --disble-gpu

**Comment by KELiON** [comment]
Nice! Closing the issue

**Comment by jjnilton** [comment]
@KELiON it worked fine with `--use-gl-=angle`! Thanks @megamorphf!
