### ISSUE TITLE
shortcut to clipboard

### ISSUE THREAD

**Issue by horusra** [KELiON/cerebro#61]
would be great to have a shortcut that instead of opening the link in browser, would just copy the link of it to clipboard (and close app)

for example, search for a gif, imdb movie or anything else, instead of pressing 'Enter' to open in browser, press 'Shift Enter' to copy link to clipboard to immediately share in IM or social media or elsewhere.

**Comment by rokcarl** [comment]
I would need something similar for math.
Let's say you have a long computation like `2+3` and you see the end result of `5` and I'd like to copy the result to the clipboard so I can paste it into the email / Slack. This is what Alfred app on the Mac does, pretty nifty.

**Comment by Kageetai** [comment]
Plugins can define their own actions for keyDown on the result, so for example the gif search just copies the URL of the GIF selected to the URL. So for now it is up to the plugins to decide that. But I guess an additional keyboard shortcut, also shouldn't be too hard :)

**Comment by KELiON** [comment]
@horusra @rokcarl @Kageetai currently for most results you can use cmd+c to copy something to clipboard (it is movie url for imdb, gif url, math result, path to file).

Only one problem that it works only on mac, because it is hardcoded to cmd+c, but on linux/windows you don't have cmd key:) It is known bug  and will be fixed in next next release for windows and linux

**Comment by rokcarl** [comment]
Ah yes, this works for _my_ usecase.

**Comment by tnguyen14** [comment]
Is it possible for the copy action to be default when pressing "Enter", instead of having to do "cmd+c" or "ctrl+c"?

**Comment by KELiON** [comment]
@tnguyen14 in which cases do you want it?

**Comment by tnguyen14** [comment]
Even just for regular math calculation. It's easier to type, say `2 + 1 <Enter>`, then having to remember that I want to copy that, and use "Ctrl+c". `<Enter>` is already the default action for many things, such as search.

**Comment by KELiON** [comment]
@tnguyen14 agree, it makes sense to add this as default action for calculator!
