### ISSUE TITLE
translation options

### ISSUE THREAD

**Issue by horusra** [KELiON/cerebro#64]
please include settings to change translator service to other popular online translators. Yandex is very limited in language support. (very few languages)

**Comment by KELiON** [comment]
@horusra do you have a list of languages that you need?

**Comment by horusra** [comment]
I mostly need Dutch, and Persian

**Comment by elmerehbi** [comment]
French & English would be great with Google Translate?

**Comment by KELiON** [comment]
@elmerehbi unfortunately only yandex.translate is supported now, but it has French and English. Google doesn't provide good and free way to have an access to Google translate.

Plugin tries to understand source language and based on source language and your system language guess what is the target language.
