### ISSUE TITLE
I have installed it from the releases page

### ISSUE THREAD

**Issue by Aminadav** [KELiON/cerebro#77]
And I don't see any plugin except `translate` and `calc`. 

For example, I don't see the ip plugin

![image](https://cloud.githubusercontent.com/assets/3584317/22564500/70b7dbf6-e98d-11e6-9722-551ee6c9dc8c.png)

And `gif` plugin.

![image](https://cloud.githubusercontent.com/assets/3584317/22564522/7d8d2fde-e98d-11e6-85bf-a798fac2566c.png)

Do I need to install anything?

**Comment by maximbaz** [comment]
Type `plugins` :wink:

**Comment by Aminadav** [comment]
Thanks.
