### ISSUE TITLE
npms.io doesn't update very frequently

### ISSUE THREAD

**Issue by codingmatty** [KELiON/cerebro#79]
I was wondering if there was a way to use npm API directly vs npms.io.

Every time I create/update a plugin, it takes a long time for npms.io to figure it out.. 

At the time of this writing, npms.io has not yet figured out that this repo has been published: https://www.npmjs.com/package/cerebro-osx-eject
And this one is on v1.0.1: https://www.npmjs.com/package/cerebro-hash

**Comment by KELiON** [comment]
@codingmatty I didn't find a way to search in npm API directly (by label `cerebro-plugin`). If we find a way to do it – we can use it

**Comment by codingmatty** [comment]
Yea, after posting this I went to look for an npm API and just found this repo where they are talking about working on the public API, but it's not ready yet..  https://github.com/npm/public-api
So, I just took to twitter and got them to update those repos on npms.io ;p
They said it should only take 5 mins or so, and the bug I noticed should be fixed as of the next release, so I will close this issue.
