### ISSUE TITLE
Not working because of a missing /var/lib/dbus/machine-id on fedora 25

### ISSUE THREAD

**Issue by edlefebvre** [KELiON/cerebro#86]
Cerebro is not working on fedora 25 out of the box. It seems that the file `/var/lib/dbus/machine-id` is needed but not found.

If you do a `ln -s /etc/machine-id /var/lib/dbus/machine-id` Cerebro works.

**Comment by KELiON** [comment]
Hey, @edlefebvre! Is known issue (#41) and already fixed, but I didn't release this fix yet. If you want you can use one these test builds: 

https://www.dropbox.com/s/wkc1lncjtx00rpy/Cerebro%20Setup%200.2.3.exe?dl=0
https://www.dropbox.com/s/7y7hrn0epfjanjm/cerebro_0.2.3_amd64.deb?dl=0
https://www.dropbox.com/s/lu5r4k6b18xwzev/cerebro-0.2.3-x86_64.AppImage?dl=0
https://www.dropbox.com/s/vslg5zsl7ruluu1/Cerebro-0.2.3.dmg?dl=0
