### ISSUE TITLE
Minimum word length to search (windows | v0.2.4)

### ISSUE THREAD

**Issue by AlexAlabyev** [KELiON/cerebro#88]
At the moment (on windows | v0.2.4), search results are shown after 1 character typed in, which shows so much unrelated noise:

![screenshot 722](https://cloud.githubusercontent.com/assets/13764106/22645090/56b8abe0-ec76-11e6-9e88-048416267bca.png)

Do you think it should show the result only when 3 or more characters typed in? (that would remove most of the noise) 
It's like in the Atom's code editor build-in plugin called `autocomplete-plus`. There's an option to choose how many characters it needs before doing autocomplete:
![c3](https://cloud.githubusercontent.com/assets/13764106/22645202/f7c7c7fa-ec76-11e6-86ae-e5836abff670.PNG)

I don't know if it will interfere with the "search by abbreviation feature" or something else, and wanted to bring that up to discuss here. 
What do you think?

**Comment by maximbaz** [comment]
Alternative suggestion: #91.

If that is implemented, you would usually type 1-2 characters to start a favorite app.

**Comment by KELiON** [comment]
Anyway I don't see any cons of showing results when 1-2 symbols are entered. So you either see some results or just empty results view, where first option is better
