### ISSUE TITLE
Problem with app launch (windows | v0.2.4)

### ISSUE THREAD

**Issue by AlexAlabyev** [KELiON/cerebro#89]
When you type in a search word and the name of the program shows up, you hit enter and nothing happens, it just goes back to the search bar view. (the same thing if you just click on the result with mouse). Is that a bug?

![2](https://cloud.githubusercontent.com/assets/13764106/22646114/b6942fbc-ec7b-11e6-94db-c04a9646393c.gif)

**Comment by KELiON** [comment]
Yes, it is a bug, thanks for report! 

Fix is here: https://github.com/KELiON/cerebro/releases/tag/0.2.5

**Comment by AlexAlabyev** [comment]
@KELiON I updated it to 0.2.5, unfortunately it still doesn't work. Clean reinstall didn't help either. Not sure what is the problem.

**Comment by KELiON** [comment]
@AlexAlabyev can you check that it doesn't work for all applications? Or only for some of them?

**Comment by AlexAlabyev** [comment]
@KELiON I just checked about 20 programs. None of them are getting opened. I tried to run cerebro with admin rights, didn't help. It just shows you cerebro search bar view (as it shown on the gif) after you hit enter, trying to open the program

**Comment by KELiON** [comment]
Looks like the wrong file was uploaded in release 0.2.5. I've updated .exe installer there, can you try to re-install it one more time?

**Comment by AlexAlabyev** [comment]
@KELiON I just downloaded the new .exe file and re-installed it. Now everything works! Thank you 

![3](https://cloud.githubusercontent.com/assets/13764106/22655273/b802e80a-eca0-11e6-82e6-bdd1f92e5d15.gif)
