### ISSUE TITLE
Latest build is broken

### ISSUE THREAD

**Issue by staff0rd** [KELiON/cerebro#9]
On the latest build, running either `dev` or `build && start` results in the application launching, and the main window displayed as a thin bar with no text entry visible.  Clicking in the box or typing doesn't seem to do anything, the bar remains white.

The application's icon menu toggles visibility on and off, however `Plugins` and `Preferences` just display the empty white bar if the application wasn't already visible.  `Quit Cerebro` works :)

Tested on both OSX El Capitan & Windows 10.

**Comment by staff0rd** [comment]
![image](https://cloud.githubusercontent.com/assets/6289998/21760929/e4106958-d6a3-11e6-88b1-169587f3dcea.png)

Screenshot from Win10 (I realise you don't support Windows, but the symptoms are the same on MAC OS, although the window's corners are rounded there).

**Comment by KELiON** [comment]
@staff0rd can you try to run it in development (`npm run dev`), and check what errors do you have in dev tools? You can toggle dev tools by `cmd+i`.

**Comment by staff0rd** [comment]
Mac (node v6)
~~~
Uncaught Error: Module version mismatch.  Exepcted 50, got 48. (bindings.js: 83)
~~~

Windows (node v7)
~~~
Uncaught Error: A dynamic link library (DLL) initialization routine failed. (bindings.js: 83)
~~~

To resolve these errors, the following needs to be run under the context of `cerebro/app`;

~~~
npm install --save-dev electron-rebuild

npm rebuild --runtime=electron --target=1.4.3 --disturl=https://atom.io/download/atom-shell --build-from-source
~~~

Is a PR required for this?

**Comment by KELiON** [comment]
@staff0rd it is not a code issue, it is issue with installation process. I've added npm script `rebuild` in `cerebro/app/package.json`, so you can run `npm run rebuild` from `cerebro/app` to fix it. 

I'd only add some information about fixing this issue in Readme.md.

**Comment by KELiON** [comment]
[Added](https://github.com/KELiON/cerebro/pull/13) this information to Readme
