### ISSUE TITLE
A Javascript error (windows | v0.2.4) 

### ISSUE THREAD

**Issue by AlexAlabyev** [KELiON/cerebro#90]
I got a javascript error 2 times in the last 15 minutes. Not sure what's causing the exception, but it happens when you open the search bar `ctrl + spacebar`

![c2](https://cloud.githubusercontent.com/assets/13764106/22646425/73b5bed4-ec7d-11e6-9a29-55685639e1c0.png)

and after a few minutes it follows up with like 7 or 8 similar error messages, trying to call something else in the background:

![cx5](https://cloud.githubusercontent.com/assets/13764106/22646421/6e85c01c-ec7d-11e6-98a2-2e08f135d3a1.PNG)

**Comment by KELiON** [comment]
@AlexAlabyev do you run .exe file or you run development environment by?

**Comment by AlexAlabyev** [comment]
@KELiON I run .exe (with developer mode checked in the settings). I just turned the developer mode off to see if it prevents the error.

**Comment by AlexAlabyev** [comment]
@KELiON So far, I didn't encounter the error, after I turned the developer mode off in settings.

**Comment by maximbaz** [comment]
This issue appears when we call `toggleWindow` on the window object, that has been destroyed, not hidden.

One way to repro it: open Cerebro with a shortcut, close the window with Alt+F4, open Cerebro with a shortcut again.

I didn't investigate what happens to the `mainWindow` variable in this case, but if it has some kind of a state `DESTROYED` or anything like that, we could handle that in `showWindow` and `toggleWindow` and recreate the object.

**Comment by AlexAlabyev** [comment]
It turns out, the error shows up even when the developer mode OFF. Just got the error after clean reinstall and after a few minutes got the same error.

**Comment by TheRndCoder** [comment]
![image](https://cloud.githubusercontent.com/assets/25141697/22652022/7099e05a-ec4a-11e6-9d01-768757594870.png)

This is the message I'm getting on Cerebro v 0.2.5, I tried what @maximbaz suggested to repro and the app stopped showing the error message, more like a one time thing
