### ISSUE TITLE
Closing window with Escape doesn't persist the results

### ISSUE THREAD

**Issue by maximbaz** [KELiON/cerebro#92]
Open Cerebro, type "Settings".
Uncheck `Clean results on hide`.
Hit the hotkey to close the window.
Hit the hotkey to open the window, the results are preserved.
Hit Escape to close the window.
Hit the hotkey to open the window, the results are not preserved, but should.

**Comment by KELiON** [comment]
@maximbaz I don't think that results should be there when you use esc. For me it is like cancel/reset action, not just hide the window

**Comment by maximbaz** [comment]
Do you use both hotkey and Escape to close window depending on whether you want to preserve the current search result or you want to clear it?

I always treated Escape as "hide", that's why it was surprising for me that even though I unchecked "Clean results on hide", I always get clear window. Then almost by accident I discovered that if I use hotkey to hide Cerebro (not Escape), then results are preserved. But that seems... inconsistent?

**Comment by KELiON** [comment]
@maximbaz I do! And for me, it is expected that <kbd>esc</kbd> clears input, but if I need I can just move focus another window or use hotkey to preserve result, i.e. when I want to copy something from preview to another app. 

I just checked how it works in mac's Spotlight: they reset input by <kbd>esc</kbd> and hide window when you use <kbd>esc</kbd> with empty input.

**Comment by maximbaz** [comment]
In this case I'm clearly outnumbered 😃 

It's not a big deal for me, there is <kbd>⬆</kbd> arrow that I could use to bring the last result back, I'm just going to use it then. You can close this issue if you want.

Speaking of other launchers, I believe your judgement, I have a limited experience of how it is done elsewhere (I only used one other launcher, `albert`, which treats <kbd>esc</kbd> like hide).
