### ISSUE TITLE
Most plugins don't show results on Linux

### ISSUE THREAD

**Issue by hotice** [KELiON/cerebro#93]
Most plugins don't seem to return any results on Linux and instead, you can only search the web. For example, entering "gif testing" as displayed on the gif plugin page, doesn't display any gif, but only this:

![image](https://cloud.githubusercontent.com/assets/325449/22652026/819cf9d0-ec8d-11e6-9e18-a27ea7110dbb.png)

The same occurs with: 

- the file system navigation plugin
- Emoj
- IMDB
- Caniuse
- IP 
- Kill

What works (besides opening a web search in the default browser):

- searching and launching apps
- calculator
- smart converter
- (updated) displaying a map inside the app works (I didn't know it could do this since it's not listed in the app description)

Tested in Ubuntu 16.10 64bit with the latest Cerebro 0.2.5.

**Comment by KELiON** [comment]
@hotice can you turn on developer mode from preferences, open dev. tools from tray menu → development → dev. tools (main), reload application by tray menu → development → reload and send me the output from console tab of dev. tools?

**Comment by hotice** [comment]
Sure, here's the log (logged when attempting to search for a gif):

```
The provided value 'moz-chunked-arraybuffer' is not a valid enum value of type XMLHttpRequestResponseType.
Load external plugins
[rpc] send rpc.fn.initializePlugins
[rpc] emit 15a14762394.e8c
[rpc] emit plugin.message
[rpc] send rpc.fn.getFileIcon
[rpc] send rpc.fn.getFileSize
[rpc] send rpc.fn.getFileDetails
[rpc] emit 15a147636d1.63f
[rpc] emit 15a147636d2.a07
[rpc] send rpc.fn.getFileSize
[rpc] send rpc.fn.getFileDetails
[rpc] emit 15a1476374e.d14
[rpc] emit 15a1476374e.9e1
[rpc] emit showTerm
```

**Comment by KELiON** [comment]
@hotice looks like gif plugin is not installed. When it is installed you should see this:

![image](https://cloud.githubusercontent.com/assets/594298/22658903/02fb5fd6-ec9c-11e6-89b6-7f935e6a6fb7.png)

Can you check what do you see when you type `plugins gif`?

**Comment by hotice** [comment]
Well I suck, I thought they are installed by default and I was not familiar with how to check that. So that's it. Sorry for wasting your time, closing this.

**Comment by KELiON** [comment]
@hotice you're not alone so it is my fault that a lot of people can't find them ;)
