### ISSUE TITLE
Memory leak and high CPU usage (windows)

### ISSUE THREAD

**Issue by AlexAlabyev** [KELiON/cerebro#95]
I noticed cerebro using up 560mb of RAM (maybe more, I killed the process) and 0 - 30% of CPU, just by sitting in the background.

 It's not always like that. Normally it will go up to 230mb right after the start and then after a few seconds it goes back to 4 processes 50mb in total and 0% CPU usage.

But I looked up running processes and for the second time today I noticed these high numbers. There's probably a memory leak there somewhere, maybe it's checking for something once in a while, and when something goes wrong there, it starts doing something that takes up a lot of memory. Maybe there are some problems with fallback for some `if statements` or something like that. I'm not sure.

Does anybody know what this might be about? Do you see this on other OS ?

Maybe it's a false alarm, I just noticed it today twice, so there's not enough data. Maybe it's the JS pop-up error that was causing the problem, I don't know. I'll be watching it and report if I notice it again.

**Comment by KELiON** [comment]
@AlexAlabyev no, it can't be this problem. Loos like it is something related to windows only, I'll try to find the reason

**Comment by AlexAlabyev** [comment]
Just a little update on the issue. 

I haven't encounter the problem with high resource usage, since. Not sure what the problem was.

If anybody else will encounter this, please let us know here. Maybe it's not a common problem, and we should close the issue, maybe it just was a one time thing.

**Comment by KELiON** [comment]
Moving this conversation to #118
