### ISSUE TITLE
Need help with installing plugin

### ISSUE THREAD

**Issue by codingmatty** [KELiON/cerebro#98]
I created `cerebro-osx-eject`, but when I try to install it the regular way, it gets stuck after downloading the `tgz` file. I can manually uncompress that file and mv the contents to the `node_modules` folder (as well as add the dependency to the `package.json` file), reload Cerebro, and everything works as expected. But I can't figure out why the Cerebro app can't install the plugin itself..
Everything seemed to work fine with the other plugin I created: `cerebro-hash`

**Comment by codingmatty** [comment]
Same thing just happened with `cerebro-lipsum` plugin. :(

**Comment by KELiON** [comment]
@codingmatty I have the same problem. Looks like it is some problem with tar.gz package on [this line](https://github.com/KELiON/cerebro/blob/master/app/lib/plugins/npm.js#L50). I'll try to investigate why it happens (and why it happens only with some plugins)

**Comment by KELiON** [comment]
Looks like it is [known issue](https://github.com/alanhoff/node-tar.gz/issues/38) of tar.gz package. I've downgraded it to 1.0.2 and now it works

**Comment by KELiON** [comment]
Ok, after downgrading to tar.gz@1.0.2 it works
