### ISSUE TITLE
Suggestion: selectively show preview

### ISSUE THREAD

**Issue by codingmatty** [KELiON/cerebro#99]
Basically, not every plugin display item needs the preview, so my suggestion would be to hide the preview window until the user scrolls through the selections, and when the selected item has a `getPreview` function that returns something other than `null`, then expand the preview into view. 

I was playing around with implementing this, there were just a lot of layers (i.e. lots of things have `max-width` set), so if I find time I may try to play with it again and maybe submit a PR.

**Comment by KELiON** [comment]
@codingmatty sound good for me, we can try to play with it!
